### ISSUE TITLE
Neoscrypt Crashes While mining when network problem(8.17version)

### ISSUE THREAD

**Issue by ncgege** [KlausT/ccminer#109]
Neoscrypt Crashes While mining when network problem. (the 8.17 version)
such as stratum subscribe timeout.
or  use -r 0 when stratum connect failed.
It seems that there is a bug when network interrupt.
Can you check and fix it ,thank you.

**Comment by KlausT** [comment]
Let me guess.
Linux?

**Comment by ncgege** [comment]
Sorry for my careless。 I use windows  10 X 64

**Comment by ncgege** [comment]
Can you try ccminer -r 0 -a xxxxx ,then you interrupt your network .May be you will see the miner crashes.
I've met a lot of times. when use -r 0 .if I don't use this parameter the miner may be crashe for some days.
The readme file says:-r, --retries=N       number of times to retry if a network call fails                         (default: retry indefinitely)

**Comment by KlausT** [comment]
It doesn't crash on my system.

This is with -r 0 
![](https://i.imgpile.com/nchOWP.png)

And this is with -r 2
![](https://i.imgpile.com/nch0I1.png)

Without -r option it will recover when the connection is up again:
![](https://i.imgpile.com/nchB2x.png)

**Comment by ncgege** [comment]
Thank you for you hard working for this issues, I don't konw what's wrong . May be other problems. ccminer 2.2.3 HashRate is much low than your miner program but  It doesn't crash. I'd like use your miner.
Thank you again.

**Comment by ncgege** [comment]
![ccminer-crashes](https://user-images.githubusercontent.com/25341303/34458719-26ed8292-ee18-11e7-94c7-e67c68b36f28.jpg)
crash again😂

**Comment by lyolyalya** [comment]
that's sooo windows7=)had them until upgraded to windows 10...

**Comment by ncgege** [comment]
The new version 8.18 is more stable than 8.17,It seems that neoscrypt algo not crash ^_^,Thank you KlausT!
