### ISSUE TITLE
Linux -  Unable to build

### ISSUE THREAD

**Issue by 0xicl33n** [KlausT/ccminer#11]
g++  -O3 -march=native -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16 -disable-scrypt -pthread -L/usr/local/cuda-6.5/lib  -o ccminer ccminer-cpu-miner.o ccminer-util.o ccminer-crc32.o ccminer-hefty1.o ccminer-scrypt.o ccminer-hashlog.o heavy/heavy.o heavy/cuda_blake512.o heavy/cuda_combine.o heavy/cuda_groestl512.o heavy/cuda_hefty1.o heavy/cuda_keccak512.o heavy/cuda_sha256.o keccak/cuda_keccak256.o keccak/keccak256.o ccminer-fuguecoin.o cuda_fugue256.o sph/ccminer-fugue.o ccminer-groestlcoin.o cuda_groestlcoin.o ccminer-myriadgroestl.o cuda_myriadgroestl.o JHA/jackpotcoin.o JHA/cuda_jha_keccak512.o JHA/cuda_jha_compactionTest.o cuda_checkhash.o quark/cuda_jh512.o quark/cuda_quark_blake512.o quark/cuda_quark_groestl512.o quark/cuda_skein512.o quark/cuda_bmw512.o quark/cuda_quark_keccak512.o quark/quarkcoin.o quark/animecoin.o quark/cuda_quark_compactionTest.o cuda_nist5.o blake32.o pentablake.o sph/ccminer-bmw.o sph/ccminer-blake.o sph/ccminer-groestl.o sph/ccminer-jh.o sph/ccminer-keccak.o sph/ccminer-skein.o sph/ccminer-cubehash.o sph/ccminer-echo.o sph/ccminer-luffa.o sph/ccminer-sha2.o sph/ccminer-shavite.o sph/ccminer-simd.o sph/ccminer-hamsi.o sph/ccminer-hamsi_helper.o sph/ccminer-shabal.o sph/ccminer-whirlpool.o sph/ccminer-sha2big.o sph/ccminer-haval.o qubit/qubit.o qubit/qubit_luffa512.o qubit/deep.o qubit/doom.o x11/x11.o x11/fresh.o x11/cuda_x11_luffa512.o x11/cuda_x11_cubehash512.o x11/cuda_x11_shavite512.o x11/cuda_x11_simd512.o x11/cuda_x11_echo.o x13/x13.o x13/cuda_x13_hamsi512.o x13/cuda_x13_fugue512.o x15/x14.o x15/x15.o x15/cuda_x14_shabal512.o x15/cuda_x15_whirlpool.o x15/whirlpool.o x17/x17.o x17/cuda_x17_haval512.o x17/cuda_x17_sha512.o x11/s3.o  -L/usr/lib/arm-linux-gnueabihf -lcurl -ljansson -lpthread  -lcudart -fopenmp -lcrypto -lssl  -lcrypto -lssl
ccminer-scrypt.o: In function `scanhash_scrypt':
/build/ccminer-test/scrypt.c:716: undefined reference to`sha256_transform'
ccminer-scrypt.o: In function `HMAC_SHA256_80_init':
/build/ccminer-test/scrypt.c:60: undefined reference to`sha256_transform'
/build/ccminer-test/scrypt.c:68: undefined reference to `sha256_transform'
/build/ccminer-test/scrypt.c:75: undefined reference to`sha256_transform'
ccminer-scrypt.o: In function `PBKDF2_SHA256_80_128':
/build/ccminer-test/scrypt.c:86: undefined reference to`sha256_transform'
ccminer-scrypt.o:/build/ccminer-test/scrypt.c:95: more undefined references to `sha256_transform' follow
sph/ccminer-sha2.o: In function`scanhash_sha256d':
/build/ccminer-test/sph/sha2.c:616: undefined reference to `sha256d_ms'
sph/ccminer-sha2.o: In function`sha256d_80_swap':
/build/ccminer-test/sph/sha2.c:190: undefined reference to `sha256_transform'
/build/ccminer-test/sph/sha2.c:191: undefined reference to`sha256_transform'
/build/ccminer-test/sph/sha2.c:194: undefined reference to `sha256_transform'
collect2: error: ld returned 1 exit status
make[2]: *** [ccminer] Error 1
make[2]: Leaving directory`/build/ccminer-test'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/build/ccminer-test'
make: **\* [all] Error 2

Whats causing this error?

**Comment by KlausT** [comment]
I'm not really sure what source you are using.
Are you compiling for ARM?
Is this missing in sha2.c?

```
#if defined(__arm__) && defined(__APCS_32__)
#define EXTERN_SHA256
#endif

```

And there's probably `#include "miner.h"` missing.
Maybe you could just add
`void sha256_transform(uint32_t *state, const uint32_t *block, int swap);`
