### ISSUE TITLE
Neoscrypt algorithm error

### ISSUE THREAD

**Issue by ducdan** [KlausT/ccminer#111]
When I try to run neoscrypt for CRC, this throw an error:
_Cuda error in func 'neoscrypt_init' at line 1482 : invalid device symbol._
Here is the execution: ./ccminer -a neoscrypt -o stratum+tcp://eu1.altminer.net:10004 -u CWbDzohiaLYV4r4g2U6Vwv8wQQDUjs8xKf -p c=CRC

It is run on Tesla K80 GPU, I used nvcc version 8.0 for ccminer version 2.2 and nvcc 9.1.15 for the lastest ccminer. Both options are not work

I run on Ubuntu 16.04 with the instruction at https://github.com/tpruvot/ccminer/blob/linux/INSTALL

**Comment by KlausT** [comment]
What version did you compile?
klaust or tpruvot?
For tpruvot you have to change the Makefile.am.
Replace this:
`nvcc_ARCH += -gencode=arch=compute_52,code=\"sm_52,compute_52\"`
with this:
`nvcc_ARCH += -gencode=arch=compute_37,code=\"sm_37,compute_37\"`

When you are using my version, It should work without change.

**Comment by ducdan** [comment]
It's working now with your version.
Thanks
