### ISSUE TITLE
Blake2b/Sia algorithm error

### ISSUE THREAD

**Issue by p1r473** [KlausT/ccminer#113]
Trying to mine Sia on Nicehash with KlausT 8.14-8.17 on both CUDA 8 and 9.1
Keep getting CUDA errors like below:
scanhash_sia line 225: cannot set while device is active in this process

Sometimes, the miner just kills itself before it gets this far
Sometimes it works.... Russian Roulette

Latest stable version for Sia is: 8.13. I tried all 8.14-8.17.

![image](https://user-images.githubusercontent.com/9235633/34457285-f5af4a1a-ed79-11e7-9d5c-1cd26c3f3385.png)

**Comment by KlausT** [comment]
I have started ccminer about a twenty times now trying to reproduce this, but it doesn't happen here.

**Comment by p1r473** [comment]
It is only happening on one of my rigs

Is there a way I can enable debugging logging for you?

**Comment by KlausT** [comment]
What driver version are you using?

**Comment by p1r473** [comment]
The latest 388.71
Its only happening on one of my 5 rigs. I have no idea why

**Comment by p1r473** [comment]
Is there a way I can enable debugging logging for you?

**Comment by KlausT** [comment]
I don't think we can get any more details about this error.
Is there anything different on this rig, like something running in the background that's not on the other rigs?

**Comment by p1r473** [comment]
same as all other rigs

**Comment by p1r473** [comment]
Can you implement this fix?
https://stackoverflow.com/questions/32685521/cuda-pinned-memory-implementation-error-cannot-set-when-device-is-active-in-this

"If you do a better job of cuda error checking by checking the return value of each runtime API call, you'll discover that this error is returned from the second time you call this:

cudaSetDeviceFlags(cudaDeviceMapHost);
Note that description of this runtime API call:

If the current device has been set and that device has already been initialized then this call will fail with the error cudaErrorSetOnActiveProcess.

The solution is to call the function only once, at the beginning of your application, not every time you call the addVectorGPU function. Take that call out of the addVectorGPU function, and put it in your main routine, prior to the first call of addVectorGPU."

**Comment by p1r473** [comment]
There are also a ton of other fixes if you google the error message "cannot set while device is active in this process"

I am happy to beta test the fixes for you if you can send me builds

**Comment by p1r473** [comment]
There are also a ton of other fixes if you google the error message "cannot set while device is active in this process"

I am happy to beta test the fixes for you if you can send me builds


Other info:


This is the error string for cudaErrorSetOnActiveProcess. This error is returned if one of the interop SetDevice functions is called after the primary context has been initialized. If you are on Windows and have Nsight Visual Studio Edition you can run a CUDA trace and in the CUDA Runtime API Calls page filter on kernels with errors. If you enable call stack on error in the Activity you will be able to jump to the function causing the error.



If the current device has been set and that device has already been initialized then this
call will fail with the error *cudaErrorSetOnActiveProcess*.
In this case it is necessary to reset device using *cudaDeviceReset()* before the device's
initialization flags may be set.

**Comment by KlausT** [comment]
> In this case it is necessary to reset device using cudaDeviceReset() before the device's
> initialization flags may be set.

> The solution is to call the function only once, at the beginning of your application

That's exactly what ccminer is doing:
```
if(!init)
{
	CUDA_SAFE_CALL(cudaSetDevice(device_map[thr_id]));
	CUDA_SAFE_CALL(cudaDeviceReset());
	CUDA_SAFE_CALL(cudaSetDeviceFlags(cudaDeviceScheduleBlockingSync));
```
It works:
![screenshot](https://i.imgpile.com/nc6eYl.png)

Would you please try this version?
[ccminer-cuda91.zip](https://github.com/KlausT/ccminer/files/1614022/ccminer-cuda91.zip)

**Comment by p1r473** [comment]
Unfortunately it is not working on my machine.
But, 8.13 works. You must have changed something in the related code since then. Can you check what code has changed in related lines since 8.13?
Please send me more builds to try, we will get to the bottom of this bug together! I really want to get this to work.

![image](https://user-images.githubusercontent.com/9235633/34723575-1e7f18b6-f519-11e7-94c1-c9f7486fb512.png)

**Comment by KlausT** [comment]
Between 8.13 and 8.14 I fixed the error "cannot set while device is active in this process":
https://github.com/KlausT/ccminer/commit/5150cae8706440254ca53a2975cb1cd5260301db
Did you try the latest version with cuda 8?

Maybe one of your cards is being wierd.
I should probably add the gpu number to the error message, so we can see which one it is.

**Comment by p1r473** [comment]
Because 8.13 works fine it makes me think the card is ok but the change you made above seems to cause the error not fix it :)

I can try to figure out the command line arg for running on only GPU0 (and if that fails, then GPU1 to narrow down GPU issue)

Just tried 8.18 cuda8 with Sia. I launched it 5 times (through AwesomeMiner), it killed itself each time, and the 6th time crashed drivers (nvlddmkm event 13)

However, is it possible change 5150cae is causing the issue, not fixing it? Maybe need to revert?

I am happy to keep testing as I really want it fixed. At the moment I am just using 8.13 for Sia
You can even remote into my box if you want to try yourself or just keep sending new builds

**Comment by KlausT** [comment]
Here I have the latest version with the fix reverted:
[ccminer-revertedfix-cuda8.zip](https://github.com/KlausT/ccminer/files/1617620/ccminer-revertedfix-cuda8.zip)
[ccminer-revertedfix-cuda91.zip](https://github.com/KlausT/ccminer/files/1617697/ccminer-revertedfix-cuda91.zip)

**Comment by p1r473** [comment]
It failed in a different function now. I feel like we made progress. Instead of failing in scanhash_sia it failed in sia_gpu_hash

GPU #0: Cuda error in func 'sia_gpu_hash' at line 292 : cannot set while device is active in this process.
[2018-01-10 03:06:57] stopping 6 threads
[2018-01-10 03:07:02] resetting GPUs

Also one thing I noticed is Cuda 8 Sia didn't immediately kill itself this time though

**Comment by p1r473** [comment]
One thing I noticed is Cuda 8 Sia didn't immediately kill itself this time though

**Comment by KlausT** [comment]
The other fixes between 8.13 and 8.14 are unrelated.

sia_gpu_hash' at line 292 ?
wtf

ok, try this:
[ccminer-nexttry-cuda8.zip](https://github.com/KlausT/ccminer/files/1619464/ccminer-nexttry-cuda8.zip)

I still think that there's something wrong with your system.

**Comment by p1r473** [comment]
GPU #0: Cuda error in func 'scanhash_sia' at line 227 : cannot set while device is active in this process.


So what I'm going to do now is try to run it on one card only to determine if there is an issue with a card

I'm also going to reinstall the drivers.

Do you have any other recommendations I try? 

I will post back with results

**Comment by p1r473** [comment]
Looks like upgrading to the latest drivers fixed it. So sorry.
Please post a litecoin address so I can tip you for your time
