### ISSUE TITLE
Low hashrate, error. 

### ISSUE THREAD

**Issue by XxMetalMartyrxX** [KlausT/ccminer#114]
I'm getting extremely low hashrates with this. Rocking only about 800kh/s on a 1070, and 500kh/s on 1060 3GB on Neoscrypt. When using Alexis for NIST5 however, I get expected hashrates. When I tweak intensity to 16.2, I get this error: https://gyazo.com/769abdf1b82be97f4d37eab7826dd015

Motherboard: Biostar TB 250
PSU: Rosewill 1000watt semi modular
CPU: Celeron 3930
Mining Software: CC Miner Klaust 8.17
PCIE Risers: https://www.amazon.ca/gp/product/B072XJ8N57/ref=oh_aui_detailpage_o09_s01?ie=UTF8&psc=1
OS: Windows 10 64 Bit
GPU: 6x 1060, 1x 1070
OC: +500 mem +150 clock
EDIT: Here's a screen cap of one of the 1060's. https://gyazo.com/e16987d651f09d9b1169e5fc801001c5

**Comment by lyolyalya** [comment]
seems like you are using not klausT miner cause founded share is marked YES! and klausT miner mark it with YAY!
your hashrate more like tpruvots ccminer.

**Comment by XxMetalMartyrxX** [comment]
I'm using klaust. https://gyazo.com/b657164a50331d264379dbcc73f985a8
Screenshotted another miner, let me update the screenshot.

**Comment by lyolyalya** [comment]
last screenshot - yes.so what's next?where are shares?errors?

**Comment by XxMetalMartyrxX** [comment]
Updated @lyolyalya

**Comment by lyolyalya** [comment]
i see.pagefile?i had mininmum 24GB for 17 intensity.aand what PL are you using?neoscrypt hashrate is dramatically falls down with lowering PL.

**Comment by XxMetalMartyrxX** [comment]
24gb of ram? I have PL? Lol I'm not very adept with mining lingo haha.

**Comment by lyolyalya** [comment]
24GB PAGEFILE.VIRTUAL MEMORY? PL is Powerlimit of the card?100%?80%?

**Comment by XxMetalMartyrxX** [comment]
Yeah I have 25gb of virtual memory set right now. Powerlimit is set to 100%. Some people are telling me intensity should be around 21 with these cards. But as soon as I go over 16.1 it errors.

**Comment by lyolyalya** [comment]
for neoscrypt 17.6 - is the max for 1080-1080ti.for 1060 and 1070 - 16-17.hashrate is preety low.must be at least 600 kh on 1060 Gb...

**Comment by XxMetalMartyrxX** [comment]
Interesting. I'm stumped. On my gaming computer, I was running my 1070 around 1100kh/s. Now on my mining rig I'm only getting 800kh/s out of it. Ugh.

**Comment by lyolyalya** [comment]
maybe its related to win 10 version like it was with ethereum.neoscrypt cares about memory...what win 10 release are you using on the rig?must be at least unniversary update.

**Comment by XxMetalMartyrxX** [comment]
I do have some windows updates queued, I'll do them right now and come back. Thank you for your willingness to help. Much appreciated.

**Comment by XxMetalMartyrxX** [comment]
So, it was because I wasn't on the latest version of windows. Thank you for your help!
