### ISSUE TITLE
Tribus CCMiner-x64 2.2.1  Result not valitade on cpu

### ISSUE THREAD

**Issue by hierzn** [KlausT/ccminer#115]
Hey bois! 
I read most of the Issues on other sides and nothing helped.. 
I have a win 10 and 6 1070 GTX Cards with 388.71 Drivers

after about 10-15 minutes it keeps crashing.. with that message..
(screenshot)
https://screenpresso.com/=TiACf

I tried to reduce intensity --> no help
tried other miners --> no help
on every other algo it works fine.. run 3 days without an error on neoscrypt .. 
maybe you guys can give me a little hint..

**Comment by lyolyalya** [comment]
klaust miner does not support tribus algo as far as i know.you need to write to tpruvots bitcointalk thread.

**Comment by hierzn** [comment]
Ok thanks.. haven't found somehing.. but found his old version.. this works fine but losing about 20% hashrate.. (better then nothing) thanks for info

**Comment by lyolyalya** [comment]
you are on github dude.that's so simple...

https://github.com/tpruvot/ccminer/releases

**Comment by hierzn** [comment]
I am new to this thing here D thanks for help
