### ISSUE TITLE
out of memory on Lyra2rev2 algo

### ISSUE THREAD

**Issue by bakeneko1** [KlausT/ccminer#119]
Hello, 
got an error:
Cuda error in func 'scanhash_lyra2v2' at line 159 : out of memory.
on 1080 ti cards
release 8.18 cuda 9.1

**Comment by KlausT** [comment]
You have set the intensity too high.

**Comment by 7h3Cub3** [comment]
It can also be that you didn't set your virtual memory high enough (try to have at least 7GB per card)

**Comment by bakeneko1** [comment]
7h3Cub3 it seems so. increasing the windows swap solved the problem. Thanks.
