### ISSUE TITLE
Error when calling via C++ CreateProcess (Windows 10 x64)

### ISSUE THREAD

**Issue by DarkMatterMatt** [KlausT/ccminer#122]
### Doesn't work
(ccminer path in the application name, arguments in the command line parameter, `-i 15` or `-a lyra2v2` as the first argument):
```
    CreateProcess(
        TEXT("C:\\crypto\\ccminer-818-cuda91-x64\\ccminer.exe"),
        TEXT("-i 15 -q -a lyra2v2 -o stratum+tcp://xvg-mine.idcray.com:10011 -u user -p pass"),
        NULL, NULL, FALSE,
        0, NULL, NULL,
        &startupInfo,
        &processInfo
    );
```
CCMiner throws an error:
`-i: unsupported non-option argument '15'`
https://github.com/KlausT/ccminer/blob/0a5c4dbcd45fd23c6b6936400368341a47a0a2ac/ccminer.cpp#L2650-L2655

### Does work
(using NULL as the application name, with the path in the command line parameter):
```
    CreateProcess(
        NULL,
        TEXT("C:\\crypto\\ccminer-818-cuda91-x64\\ccminer.exe -i 15 -q -a lyra2v2 -o stratum+tcp://xvg-mine.idcray.com:10011 -u user -p pass"),
        NULL, NULL, FALSE,
        0, NULL, NULL,
        &startupInfo,
        &processInfo
    );
```

### Does work
(ccminer path in the application name, arguments in the command line parameter, `-q` as the first argument):
```
    CreateProcess(
        TEXT("C:\\crypto\\ccminer-818-cuda91-x64\\ccminer.exe"),
        TEXT("-q -i 15 -a lyra2v2 -o stratum+tcp://xvg-mine.idcray.com:10011 -u user -p pass"),
        NULL, NULL, FALSE,
        0, NULL, NULL,
        &startupInfo,
        &processInfo
    );
```

### Does work
(using the path as the application name, with the path also in the command line parameter):
```
    CreateProcess(
        TEXT("C:\\crypto\\ccminer-818-cuda91-x64\\ccminer.exe"),
        TEXT("C:\\crypto\\ccminer-818-cuda91-x64\\ccminer.exe -i 15 -q -a lyra2v2 -o stratum+tcp://xvg-mine.idcray.com:10011 -u user -p pass"),
        NULL, NULL, FALSE,
        0, NULL, NULL,
        &startupInfo,
        &processInfo
    );
```

**Comment by KlausT** [comment]
When the application name is not NULL then you also need the application name as the first parameter in the command line (because argv[0] is the app name).

Quote from Microsoft:

> Console processes written in C can use the argc and argv arguments to parse the command line. Because argv[0] is the module name, C programmers generally repeat the module name as the first token in the command line.

**Comment by DarkMatterMatt** [comment]
Ok, I _was_ wondering if that was the reason, I think it's weird that it works in the third scenario then.
