### ISSUE TITLE
Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1476 : unspecified launch failure

### ISSUE THREAD

**Issue by boro2000** [KlausT/ccminer#123]
After mining NeoScrypt for some minutes with a superb hashrate, the miner v8.18 always crashes with the following error(s)

Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1476 : unspecified launch failure.
Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1462 : unspecified launch failure.

The miner runs on Windows10 with six dedicated Nvidia ASUS Strix GTX 1070 OC graphic cards, driver version 388.71. All cards are set to 80% power and +600 memory clock (resulting in 4404MHz), using MSI Afterburner. Temperature is always well below 60° for each card.

I tried to set the intensity to 14,15,16,17 and 21, but the result is always the same.

What I noticed is, that MSI Afterburner sometimes reports a short spike of the memory clock to 4604MHz (!) for one random graphics card, just before the crash happens. Actually, that should not happen at all, and may be only some measure fault of the Afterburner. But who knows!

**Comment by KlausT** [comment]
I think that the overclocking may be a problem.
With my 1070 I can use -i 17.6 without problem, but I don't overclock.

**Comment by lyolyalya** [comment]
that's an overclock.and you need to activate p0 state mode to avoid this memory spikes with nvidiaprofile inspector.

**Comment by boro2000** [comment]
Thank you, for your replies.

For Pascal graphic cards I found no way to activate P0 state.
But - setting all memory overclocking to zero did the job. I now saved all cards to one specific profile (using +0 memory overclocking) in MSI Afterburner and load this by command line in a batch file, before running the miner.

**Comment by lyolyalya** [comment]
i told you=)the fresh nvidiaprofile inspector does P0 state

**Comment by elinton** [comment]
Hello.
Can you pass the batch file example you did?

**Comment by lyolyalya** [comment]
what batfile?
https://img.techpowerup.org/180707/p1kalmig2k294.jpg

**Comment by elinton** [comment]
Thanks
