### ISSUE TITLE
Blue Text with stratum and Block info into cmd lines

### ISSUE THREAD

**Issue by EntropyManaged** [KlausT/ccminer#127]
I noticed that my machines that run on MPM every so often in the command window, will flash in blue text a stratum for hash refinery and also the block # that the shares are being submitted against.  My other machine is just direct mining to hash refinery with KlaustCCminer and I never see that blue block data flash in between the reported hash rates for the GPUs. Is that an option I can add to the .bat file or is it something specific to MPM?

**Comment by KlausT** [comment]
How many of those lines you see depends on the pool.
Usually at least once per minute.
When you are using the -q option for ccminer then you will only see the shares, but not the blue lines.
But as long as you see "accepted" messages everything is ok.

**Comment by EntropyManaged** [comment]
@KlausT  Thanks for the prompt reply!
