### ISSUE TITLE
fatal error: nvapi/nvapi_ccminer.h: No such file or directory

### ISSUE THREAD

**Issue by blubyu** [KlausT/ccminer#128]
Just pulled the latest changes and tried to build and got the above error.  autogen.sh and configure.sh run just fine.  Once I run build.sh I get the error above.  Any ideas?

nvml.cpp:26:33: fatal error: nvapi/nvapi_ccminer.h: No such file or directory
compilation terminated.
Makefile:1327: recipe for target 'ccminer-nvml.o' failed
make[2]: *** [ccminer-nvml.o] Error 1

**Comment by KlausT** [comment]
Yeah, the Linux build is messed up after the latest change.
I forgot to change the Makefile.am, and there's probably a bug in the api code

**Comment by blubyu** [comment]
Thanks for the quick response.  I will pull again later tomorrow and see if it is working.  If not, I will just wait :)
