### ISSUE TITLE
This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

### ISSUE THREAD

**Issue by mirnyyy** [KlausT/ccminer#13]
Making all in jansson
make[3]: Entering directory `/home/ubuntu4/ccminer/compat/jansson'
make[3]: Nothing to be done for`all'.
make[3]: Leaving directory `/home/ubuntu4/ccminer/compat/jansson'
make[3]: Entering directory`/home/ubuntu4/ccminer/compat'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory`/home/ubuntu4/ccminer/compat'
make[2]: Leaving directory `/home/ubuntu4/ccminer/compat'
make[2]: Entering directory`/home/ubuntu4/ccminer'
/usr/local/cuda/bin/nvcc -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_32,code=\"sm_32,compute_32\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -I/usr/local/cuda/include -I. -O3 -Xcompiler -Wall -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o heavy/heavy.o -c heavy/heavy.cu
/usr/local/cuda/bin/nvcc -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_32,code=\"sm_32,compute_32\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -I/usr/local/cuda/include -I. -O3 -Xcompiler -Wall -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o heavy/cuda_blake512.o -c heavy/cuda_blake512.cu
/usr/local/cuda/bin/nvcc -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_32,code=\"sm_32,compute_32\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -I/usr/local/cuda/include -I. -O3 -Xcompiler -Wall -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o heavy/cuda_combine.o -c heavy/cuda_combine.cu
/usr/local/cuda/bin/nvcc -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_32,code=\"sm_32,compute_32\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -I/usr/local/cuda/include -I. -O3 -Xcompiler -Wall -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o heavy/cuda_groestl512.o -c heavy/cuda_groestl512.cu
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from ./cuda_helper.h:7,
                 from heavy/cuda_blake512.cu:4:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: **\* [heavy/cuda_blake512.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from ./cuda_helper.h:7,
                 from heavy/cuda_groestl512.cu:7:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from ./cuda_helper.h:7,
                 from heavy/cuda_combine.cu:3:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: **\* [heavy/cuda_combine.o] Error 1
make[2]: **\* [heavy/cuda_groestl512.o] Error 1
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from ./sph/sph_types.h:828,
                 from ./sph/sph_keccak.h:44,
                 from heavy/heavy.cu:11:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: **\* [heavy/heavy.o] Error 1
make[2]: Leaving directory `/home/ubuntu4/ccminer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/ubuntu4/ccminer'
make: **\* [all] Error 2

Hi, I'm getting this error, don't you know what could possibly go wrong?
Thank you.

**Comment by KlausT** [comment]
I have no clue about linux stuff, but I would guess adding -std=c++11 to the compiler options in configure.sh would probably fix this.

**Comment by pallas1** [comment]
I would not change configure.sh, maybe configure.ac or Makefile.ac
BTW you can get around the issue quickly by running ./configure CXXFLAGS="-std=c++11"
Not sure it's CXXFLAGS or CPPFLAGS...
