### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by ghost** [KlausT/ccminer#139]
Sorry, i am completely new to this!

I just stumbled over a website which claims your ccminer-mod to have the best mining performance for my graphicscard in neoscrypt. 
So i downloaded your files, but cannot find a solution to get it to work.
Could anyone help me there?

Thanks!

**Comment by KlausT** [comment]
Windows or Linux?
The easiest way on Windows is to create a BAT file, like ccminer.bat, and then adding lines like this:
```
@echo off
c:\somewhere\ccminer.exe -a neoscrypt -o stratum+tcp://examplepool.com:3341 -O exampleuser:examplepassword
pause
```

**Comment by ghost** [comment]
Thanks for your quick response.
The platform i'm running is windows - but there is no .exe file i could adress with a batch file. 
The files i downloaded from your page are only .c or .cpp etc., so nothing i could execute on windows.

**Comment by SLM22** [comment]
@Backshift - download the cuda9 zip file and extract in Windows.  Create a new text document with Notepad and paste in the information in KlausT's quote.  Input the correct directory where the ccminer.exe file is, pool address and port, along with your mining target address. Then save the file as "something.bat" and make sure you select "all files" for the file type.  Now you can click on the newly created .bat file and the miner should start.

**Comment by ghost** [comment]
Thank you two for your help and sorry for me being such a newby, but where can i download the ccminer.exe? I can only see ccminer.cpp, ccminer.sln, ccminer.vcxproj and ccminer.vcxproj.filters, but no ccminer.exe

**Comment by kaos-1** [comment]
https://github.com/KlausT/ccminer/releases

**Comment by dzaraev** [comment]
sorry but where is ccminer let you set up payout address in case of solo mining (no pools)?

**Comment by SLM22** [comment]
@Backshift - you can download the .zip file at the link provided by kaos-1. Once you click there follow the steps above.

**Comment by ghost** [comment]
@SLM22 @kaos-1 @KlausT 
Thanks guys, i was actually not able to find it. I am a bit shocked...
