### ISSUE TITLE
Memory leak in neoscrypt?

### ISSUE THREAD

**Issue by kkkrackpot** [KlausT/ccminer#145]
Hi,

I noticed that neoscrypt eats quite a lot of GPU memory. 
On my 1060 3G it fills nearly all 3Gb when intensity is `-i 16`.
Is it normal or it can be a mem leak somewhere?

**Comment by KlausT** [comment]
Neoscrypt uses a lot of memory, that's normal.

**Comment by kkkrackpot** [comment]
Thanks!

**Comment by gofmar** [comment]
☺☺😊
