### ISSUE TITLE
Linux compiling error - undefined references

### ISSUE THREAD

**Issue by crazydoc72** [KlausT/ccminer#151]
Hi,
I have four rigs here, all running Xubuntu 16.04.3 with kernel 4.10.0-42, cuda 9.0 and nvidia-driver 384.81. On three rigs, ccminer compiles and runs without any problems. However, on the fourth rig, I am running into compiling errors. I´ve tried:

- CUDA-8.0
- CUDA-9.0
- gcc-4.8
- gcc-5.4
- gcc-6.3

All the attempts are failing with this:
("Nicht definierter Verweis" translates into "undefined reference", i think...)

`g++  -O3 -march=native -std=c++11 -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16 -fno-strict-aliasing -pthread -L/usr/local/cuda/lib64 -ldl  -o ccminer ccminer-crc32.o ccminer-hefty1.o ccminer-ccminer.o ccminer-util.o ccminer-api.o ccminer-hashlog.o ccminer-nvml.o ccminer-stats.o ccminer-sysinfos.o ccminer-cuda.o sph/ccminer-neoscrypt.o sph/ccminer-sha256_Y.o sph/ccminer-sph_sha2.o ccminer-fuguecoin.o Algo256/cuda_fugue256.o sph/ccminer-fugue.o ccminer-groestlcoin.o cuda_groestlcoin.o ccminer-myriadgroestl.o cuda_myriadgroestl.o lyra2/ccminer-Lyra2.o lyra2/ccminer-Sponge.o lyra2/lyra2REv2.o lyra2/cuda_lyra2v2.o Algo256/cuda_blake256.o Algo256/cuda_groestl256.o Algo256/cuda_keccak256.o Algo256/cuda_skein256.o Algo256/cuda_bmw256.o Algo256/cuda_cubehash256.o Algo256/blake256.o Algo256/keccak256.o JHA/jackpotcoin.o JHA/cuda_jha_keccak512.o JHA/cuda_jha_compactionTest.o cuda_checkhash.o quark/cuda_jh512.o quark/cuda_quark_blake512.o quark/cuda_quark_groestl512.o quark/cuda_skein512.o quark/cuda_bmw512.o quark/cuda_quark_keccak512.o quark/cuda_jh512keccak512.o quark/quarkcoin.o quark/cuda_quark_compactionTest.o cuda_nist5.o pentablake.o skein.o Sia/sia.o Sia/cuda_sia.o sph/ccminer-bmw.o sph/ccminer-blake.o sph/ccminer-groestl.o sph/ccminer-jh.o sph/ccminer-keccak.o sph/ccminer-skein.o sph/ccminer-cubehash.o sph/ccminer-echo.o sph/ccminer-luffa.o sph/ccminer-sha2.o sph/ccminer-shavite.o sph/ccminer-simd.o sph/ccminer-hamsi.o sph/ccminer-hamsi_helper.o sph/ccminer-shabal.o sph/ccminer-whirlpool.o sph/ccminer-sha2big.o sph/ccminer-haval.o qubit/qubit.o qubit/qubit_luffa512.o qubit/deep.o qubit/doom.o x11/x11.o x11/fresh.o x11/cuda_x11_luffa512.o x11/cuda_x11_cubehash512.o x11/cuda_x11_shavite512.o x11/cuda_x11_simd512.o x11/cuda_x11_echo.o x11/cuda_x11_luffa512_Cubehash.o x13/x13.o x13/cuda_x13_hamsi512.o x13/cuda_x13_fugue512.o x15/x14.o x15/x15.o x15/cuda_x14_shabal512.o x15/cuda_x15_whirlpool.o x15/whirlpool.o x17/x17.o x17/cuda_x17_haval512.o x17/cuda_x17_sha512.o x11/s3.o x11/c11.o bitcoin.o cuda_bitcoin.o x15/cuda_whirlpoolx.o x15/whirlpoolx.o neoscrypt/neoscrypt.o neoscrypt/cuda_neoscrypt.o neoscrypt/cuda_neoscrypt_tpruvot.o -L/usr/lib/x86_64-linux-gnu -lcurl -ljansson -lpthread  -lcudart -fopenmp -lcrypto -lssl  -ldl -lcrypto -lssl
ccminer-ccminer.o: In Funktion `main':
ccminer.cpp:(.text.startup+0xa11): Nicht definierter Verweis auf `nvs_init()'
ccminer-nvml.o: In Funktion `nvml_reset_clocks(nvml_handle*, int)':
nvml.cpp:(.text+0x1073): Nicht definierter Verweis auf `nvs_reset_clocks(int)'
collect2: error: ld returned 1 exit status
Makefile:820: die Regel für Ziel „ccminer“ scheiterte
make[2]: *** [ccminer] Fehler 1
make[2]: Verzeichnis „/home/andreas/work/ccminer.klaus“ wird verlassen
Makefile:1436: die Regel für Ziel „all-recursive“ scheiterte
make[1]: *** [all-recursive] Fehler 1
make[1]: Verzeichnis „/home/andreas/work/ccminer.klaus“ wird verlassen
Makefile:503: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
`

**Comment by KlausT** [comment]
Oops. Forgot to add a file to Makefile.am.

**Comment by crazydoc72** [comment]
'git pull' updates Makefile.am, so let´s start the build process again. May take some time on an ancient Core2Duo E6420 ;-)

Update: Builds & runs like a flaw now! Gives me ~20% higher hash rate than the other ccminers :-)

**Comment by Renatfg** [comment]
Please share instruction to build under Linux, or where i can get binary file for Linux?

**Comment by Chovus13** [comment]
Vote for instructions, please. Thanks

**Comment by KlausT** [comment]
Installing all the dependencies is the tricky part.
Someone who is using Linux (not me) should be answering this.
The last part is easy:
`./build.sh`

**Comment by crazydoc72** [comment]
Ok, where should I start? Do you guys already have Linux installed? I can only help you with Ubuntu, preferably version 16.04.3, cause I don´t use other distros.
