### ISSUE TITLE
do i need to download and install CUDA 8.0?

### ISSUE THREAD

**Issue by RockZhou8** [KlausT/ccminer#16]
though i see  the  lastest version of CCminer have switched to CUDA 8.0

**Comment by auroracoin** [comment]
Good question Rock... do we need CUDA 8.0 ?

**Comment by KlausT** [comment]
You only need to install CUDA if you want to compile it yourself.
You could then use CUDA 7.5 or 6.5 as well, but I don't see why.
Updating your driver is probably a good idea when your version is too old.
