### ISSUE TITLE
--background option not working

### ISSUE THREAD

**Issue by MrNoobie07** [KlausT/ccminer#166]
Hello i've been trying to run the backgound option but it doesn't work
![image](https://user-images.githubusercontent.com/35643292/35189099-6853bf8c-fe4c-11e7-8cc3-35a6068bd0a4.png)

**Comment by KlausT** [comment]
The background option is only being used under Linux.
I don't actually know what this is supposed to do there.

**Comment by MrNoobie07** [comment]
The classic ccminer works perfect with background option.
If you can enable it would be perfect.
Thank you for your answer

**Comment by KlausT** [comment]
Should be fixed now.
Try this:
[ccminer-819-jan21-cuda91-x64.zip](https://github.com/KlausT/ccminer/files/1650217/ccminer-819-jan21-cuda91-x64.zip)

**Comment by MrNoobie07** [comment]
Works Perfect!!! Thank you!
