### ISSUE TITLE
Scrypt-N uses 1 CPU core per GPU

### ISSUE THREAD

**Issue by mminolli** [KlausT/ccminer#175]
As one can imagine: if one has a multi-GPU rig with a single-core CPU, then one can only mine Scrypt-n with a single GPU.

Worth noting this is not an issue with sgminer.

**Comment by KlausT** [comment]
actually, you can't mine it at all with this ccminer version

**Comment by priyavadan** [comment]
any plans to add support for scrypt-n please?
