### ISSUE TITLE
Hashrate drop on 8.19 higher with 8.18

### ISSUE THREAD

**Issue by cowokjojo** [KlausT/ccminer#179]
i check history 8.19 said more hash rate, but why hashrate drop, i do not compare result on pool
Is the default intensity is drop (for 1070 intensity 15.25)
I use gigabyte GTX1070 8GB
When using ccminer-alexis default intensity is 16

**Comment by cowokjojo** [comment]
I am using neoscrypt algo

**Comment by kaos-1** [comment]
Default intensity is too low for 1070, (15.25), use intensity -i 17.6 instead.

**Comment by kaos-1** [comment]
here is what you should get on 1070 with intensity 17.6

![1070 intensity -17 6](https://user-images.githubusercontent.com/34693864/35434712-5e9a2fae-0288-11e8-82da-7efbe4f93a2d.png)

**Comment by georgeous30** [comment]
@kaos-1 how you choose 17.6 intensity for 1070?

**Comment by kaos-1** [comment]
i pasted above add  -i 17.6   into your bat file.

**Comment by georgeous30** [comment]
i mean, how to calculate the intensity for specific gpu? @kaos-1

**Comment by ultiman2** [comment]
yeah me too i want to know how can we choose the right intensity?
for my 1060 i choose 16 and so far i dont have any problem but can i go higher?

**Comment by KlausT** [comment]
With higher intensities you usually get higher speeds.
Just try higher values until you get errors.

**Comment by kaos-1** [comment]
It's definitely trial and error, i max out my gpu memory at 17.6 so that is max on neoscrypt 17.7 u run into out of memory errors. But always use decimals to fine tune, most just use whole numbers and loose out on some extra hash sitting there for taking.
