### ISSUE TITLE
Skein 3rd GPU

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/ccminer#18]
Hello.have 3x1070 GTX Armor 8G oc.when mining skein my 3rd gpu is dissapearing from thread meter.but gpu load is 95% still...then smaller hashrate...tpruvot miner is okay.but yours give bigger hasrates.problem on all version starting 8-8.03 x86 and x64.

**Comment by KlausT** [comment]
I think this is probably a hardware problem.
After looking at the code I can't see a reason why the 3rd card shouldn't work.

**Comment by lyolyalya** [comment]
i shuffled cards.now my 3rd card with micron is 1st.and again.other algos and miners is fine...there is a lot of duplicate shares.skein only.maybe intensity is a problem?what intensity is suggested?
![default](https://cloud.githubusercontent.com/assets/16507768/21109027/f06f728a-c09f-11e6-995e-07b72f41cefa.PNG)

**Comment by KlausT** [comment]
Version 8.04 should fix the duplicate shares.
On my card intensities up to 27 or 28 are no problem, but my card is not overclocked at all.

**Comment by lyolyalya** [comment]
somehow this duplicate share fix is fixing 3r gpu issue too=)thanks a lot=)
