### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ghost** [KlausT/ccminer#187]
Hi, I have the latest version running on my windows 10 64. Each time I try to start it I get "the application stopped working" and I have to close. I tried totally disabling any overclock and I still get the same problem.
Any help would be appreciated!

**Comment by ghost** [comment]
Here is a screenshot 
<img width="933" alt="klaust" src="https://user-images.githubusercontent.com/35937463/35534397-b086c1aa-0540-11e8-9075-322c6aed4222.png">

**Comment by ghost** [comment]
I have found the problem. It crash when I try to use it with Equihash. I think it's not compatible right? Where can I find the list of the compatible algos for this miner?

**Comment by KlausT** [comment]
The --help option shows all the algos, or you can see it in the Readme file
