### ISSUE TITLE
Complation error

### ISSUE THREAD

**Issue by stasxpulse** [KlausT/ccminer#189]
Hi,

I have an issue with compilation on ccminer on Ubuntu, is someone can provide any help?

ptxas info    : Used 72 registers, 4096 bytes smem, 344 bytes cmem[0], 72 bytes cmem[2]
rm: cannot remove 'ccminer': Is a directory
Makefile:1184: recipe for target 'ccminer' failed
make[2]: *** [ccminer] Error 1
make[2]: Leaving directory '/root/ccminer-tpruvot-git'
Makefile:2201: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/ccminer-tpruvot-git'
Makefile:654: recipe for target 'all' failed
make: *** [all] Error 2

Thanks,

**Comment by nazerim** [comment]
The error occurred earlier - run "make" again and post the whole output log

**Comment by KlausT** [comment]
This is not the right place to discuss problems with tpruvot's ccminer version
