### ISSUE TITLE
difficulty d=1024 or d=2048

### ISSUE THREAD

**Issue by lowenheart** [KlausT/ccminer#192]
when I didnt set the stratum diff sometime get 5500. how to set diff if hashrate around 9600 kH/s on neoscrypt

**Comment by KlausT** [comment]
How to set the difficulty is different for every pool.

**Comment by lowenheart** [comment]
i still confused how to calculate fixed difficulty (d=(value)). I using 1070ti and mining GBX coin at altminer. I have 2 rig with same 1070ti and the one is 7 gpu and another 8 gpu. I really confused to calculate the fit difficulty setting

**Comment by KlausT** [comment]
It doesn't really matter, the amount of coins you get will be the same.
Just make sure you don't spam the pool

**Comment by lowenheart** [comment]
so it better dont put fixed diff or put fixed with 10 shared per minute? I tried to calculate to make not spam is around 10 shared accepted per minute

**Comment by KlausT** [comment]
Yeah, not more than 10 per minute
