### ISSUE TITLE
some shares will not be found

### ISSUE THREAD

**Issue by KlausT** [KlausT/ccminer#2]
Only max 1 share will be found in each hash round.
Things are worse with higher throughput and low difficulty

**Comment by sp-hash** [comment]
fixed by

tpruvot

https://github.com/tpruvot/ccminer/commit/f387898ead48530e11ca5c13395c2816a4b85067
https://github.com/tpruvot/ccminer/commit/c3bdb623e82ed4bc6906ff06d616a2b13494b424

I will merge the fixes later today.
