### ISSUE TITLE
bug in bitcoin algo

### ISSUE THREAD

**Issue by KlausT** [KlausT/ccminer#20]
There's an "unknown error" or something similar when you try to mine bitcoin.
I can't find the bug.
Yeah, I know. Nobody is mining Bitcoin with ccminer, but I want to fix the bug anyway.

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/22300688/f0b16470-e330-11e6-8e7b-e495ce9b1b68.png)
have no problem for few minutes with 8.05x64.
when you get this error?

**Comment by KlausT** [comment]
I get this after a few seconds:

![screenshot 2017-01-25 18 45 32](https://cloud.githubusercontent.com/assets/1238324/22302387/e45d0ca8-e32e-11e6-803f-1efa698fc195.png)
Looks like I will have to comment out random code lines to find out what's causing this.

**Comment by lyolyalya** [comment]
try zpool...maybe nicehash not supporting ccminer at all?

**Comment by lyolyalya** [comment]
i will try nicehash instead.

**Comment by lyolyalya** [comment]
nope.nicehash fine too...
![image](https://cloud.githubusercontent.com/assets/16507768/22303272/302f437e-e33b-11e6-92b1-cf26930e6ba1.png)

**Comment by KlausT** [comment]
That's wierd.
My card is ok, Other algos are working just fine.

**Comment by lyolyalya** [comment]
agree=)but it's fine...what OS you are using?

**Comment by KlausT** [comment]
Win 10 with the latest driver version

**Comment by lyolyalya** [comment]
same too...

**Comment by KlausT** [comment]
Do you use my binaries, or did you compile it yourself?

**Comment by lyolyalya** [comment]
i use your binaries.have no knowledge about compiling=)

**Comment by MaZyGer** [comment]
Hey KlausT. I have the same error like you with bitcoin. If I get this my screen turns black for short time. Its like if I get away from fullscreen mode. I have GTX980 Ti. But I think I haven't the latest driver ( I hate to update. Something is buggy after updates :D). Win7 and Driver Version 372.54

**Comment by KlausT** [comment]
should be fixed now
