### ISSUE TITLE
Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1474 : an illegal instruction was encountered

### ISSUE THREAD

**Issue by LiveITA** [KlausT/ccminer#207]
Hi, what you think? How shoulkd i solve this?

[2018-02-17 13:34:29] accepted: 171/171 (100.00%), 13.96 MH/s yay!!!
[2018-02-17 13:34:29] GPU #10: MSI GTX 1070 Ti, 1300.04 kH/s
[2018-02-17 13:34:30] accepted: 172/172 (100.00%), 13.96 MH/s yay!!!
[2018-02-17 13:34:31] GPU #2: MSI GTX 1070, 1102.84 kH/s
[2018-02-17 13:34:31] accepted: 173/173 (100.00%), 13.96 MH/s yay!!!
[2018-02-17 13:34:31] GPU #7: MSI GTX 1070, 1093.30 kH/s
[2018-02-17 13:34:31] accepted: 174/174 (100.00%), 13.96 MH/s yay!!!
GPU #5: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1492 : an illegal instruction was encountered.
[2018-02-17 13:34:32] stopping 12 threads
GPU #11: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #3: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1492 : an illegal instruction was encountered.
GPU #10: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #7: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1474 : an illegal instruction was encountered.
GPU #0: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1474 : an illegal instruction was encountered.
GPU #8: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #6: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #4: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #2: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #9: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
GPU #1: Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1488 : an illegal instruction was encountered.
[2018-02-17 13:34:37] resetting GPUs
ccminer 8.19-KlausT (64bit) for nVidia GPUs
Compiled with GCC 5.4 using Nvidia CUDA Toolkit 9.0

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations implemented by sp-hash, klaust, tpruvot and tsiv.

**Comment by KlausT** [comment]
Looks like you have a problem with your hardware.

**Comment by LiveITA** [comment]
It was just OC, memory clock too high. Thanks anyway
