### ISSUE TITLE
JSON-RPC call failed: Method not found

### ISSUE THREAD

**Issue by JavaMachine** [KlausT/ccminer#21]
Hello fellow developers,

I am having issue with running ccminer with bitcoin-qt.exe (Solo mining)

I am receiving error below upon start:

> [2017-01-26 14:23:57] 1 miner thread started, using 'bitcoin' algorithm
> [2017-01-26 14:23:57] Binding thread 0 to cpu 0 (mask 1)
> [2017-01-26 14:23:57] JSON-RPC call failed: Method not found
> [2017-01-26 14:23:57] json_rpc_call failed, retry after 5 seconds

my ccminer running parameters:

> ccminer -a bitcoin -o http://127.0.0.1:8332 -u USER -p 123456789 -R 5 -D

my bitcoin.conf file:

> rpcuser=USER
> rpcpassword=123456789 
> server=1
> daemon=1
> rpcallowip=127.0.0.1

my  bitcoin-qt.exe running parameters:

> "C:\Program Files\Bitcoin\bitcoin-qt.exe" -server

I thought, maybe bitcoin-qt.exe does not accepting any connections, but when I run bfgminer with parameters:

> bfgminer -S opencl:auto -o http://127.0.0.1:8332 -u USER -p 123456789 2>logfile.txt

everything works fine...

P.S. everything is up to date:
Bitcoin v0.13.2 (64 bit)
ccminer v8.05-KlausT
pthreads static 2, 9, 1, 0
libcurl/7.50.3 WinSSL WinIDN

Thanks in advance

**Comment by JavaMachine** [comment]
UPD:
I have tried above with ccminer 64 bit version, problem is still there, and added another error upon start.

> [2017-01-26 14:58:57] dlopen(126): failed to load C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll
> [2017-01-26 14:58:57] dlopen(126): failed to load nvml.dll

My GPU:

![gpu](https://cloud.githubusercontent.com/assets/5568121/22327288/45ba9d22-e3d8-11e6-8367-b6d67f0aa209.gif)

**Comment by JavaMachine** [comment]
UPD: 
I have tried to add -P into ccminer running parameters, and the result is

```
* Rebuilt URL to: http://127.0.0.1:8332/
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8332 (#1)
* Server auth using Basic with user 'USER'
> POST / HTTP/1.1
Host: 127.0.0.1:8332
Authorization: Basic xxxxxxSOME_BASE64xxx
Accept-Encoding: identity
Content-Type: application/json
Content-Length: 45
User-Agent: ccminer/8.05-KlausT
X-Mining-Extensions: longpoll noncerange reject-reason
X-Mining-Hashrate: 0

< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Thu, 26 Jan 2017 11:19:41 GMT
< Content-Length: 76
* HTTP error before end of send, stop sending
<
* Curl_http_done: called premature == 0
* Closing connection 1
[2017-01-26 16:19:41] JSON protocol response:
{
   "error": {
      "code": -32601,
      "message": "Method not found"
   },
   "result": null,
   "id": 0
}

[2017-01-26 16:19:41] JSON-RPC call failed: Method not found
[2017-01-26 16:19:41] json_rpc_call failed, retry after 30 seconds
```

**Comment by KlausT** [comment]
Sorry, but Bitcoin solo mining is no longer supported, because they removed the getwork command.
Trying to mine Bitcoin is useless anyway, the difficulty is too high.
