### ISSUE TITLE
Running Arch with Cuda 9.1: Runtime API not found

### ISSUE THREAD

**Issue by raedeus** [KlausT/ccminer#211]
It looks like the Arch installation of CUDA 9.1 places all the resources in /opt/cuda and NOT /usr/local/cuda. I am getting errors on compile that the cuda runtime api is not found. Do I need to modify some flags here? Thought I would just shoot a quick question rather than huge explanation and pasting errors. If need be I will be more than happy to.

Thanks!

raedeus

**Comment by KlausT** [comment]
You could edit the path:
https://github.com/KlausT/ccminer/blob/5da23f24c5dee2068cd321545db5ccd87aafc46d/configure.sh#L10

**Comment by raedeus** [comment]
You know what... I feel so ashamed. I am just so caught up in the coin-craze I have forgotten my basics.

ln -s /opt/cuda /usr/local/cuda

Solved.

[insert facepalm gif]
[insert bang head on brick wall gif]

Thank you for your support!

raedeus
