### ISSUE TITLE
Error building whit cuda 

### ISSUE THREAD

**Issue by rufus88** [KlausT/ccminer#215]
Hello there

I have tested whit gcc-5 and gcc-6 using the proper CC CPP CXX flgas at build time (for switch between compilers)

the same result  i get stuck here

/usr/bin/ld: x15/x14.o: relocation R_X86_64_32S against symbol `opt_benchmark' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x15/x15.o: relocation R_X86_64_32S against symbol `opt_benchmark' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x15/cuda_x14_shabal512.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x15/cuda_x15_whirlpool.o: relocation R_X86_64_32S against symbol `stderr@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x15/whirlpool.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x15/cuda_x15_whirlpool_sm3.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x17/x17.o: relocation R_X86_64_32S against symbol `opt_benchmark' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x17/hmq17.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x17/cuda_x17_haval256.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x17/cuda_x17_sha512.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/phi.o: relocation R_X86_64_32S against symbol `device_map' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/cuda_streebog_maxwell.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/c11.o: relocation R_X86_64_32S against symbol `device_map' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/s3.o: relocation R_X86_64_32S against symbol `opt_benchmark' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/sib.o: relocation R_X86_64_32S against symbol `device_map' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/veltor.o: relocation R_X86_64_32S against symbol `device_map' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: x11/cuda_streebog.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/blake.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/keccak.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/sha256.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/salsa_kernel.o: relocation R_X86_64_32S against symbol `opt_nfactor' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/test_kernel.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/fermi_kernel.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/kepler_kernel.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/nv_kernel.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: scrypt/nv_kernel2.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
**/usr/bin/ld: scrypt/titan_kernel.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:1184: recipe for target 'ccminer' failed
make[2]: *** [ccminer] Error 1**
make[2]: Leaving directory '/home/rafa/Desktop/ccminer'
Makefile:2201: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rafa/Desktop/ccminer'
Makefile:654: recipe for target 'all' failed
make: *** [all] Error 2
rafa@genia:~/Desktop/ccminer$
 

Thanks for any clues and tips you could give me to solve this. Also comment i have used clang versions 3.8 and 3.5 also tested gcc5 and gcc6

any comments?

**Comment by rufus88** [comment]
I posted here but i am using  @tpruvot version

**Comment by jaysea15** [comment]
I have the same issue, anyone find answers?

**Comment by KlausT** [comment]
I can't help you there.
Maybe ask in this forum thread, it's the official thread for tpruvot's version:
https://bitcointalk.org/index.php?topic=770064.0
