### ISSUE TITLE
About the intensity, num "F" in readme file

### ISSUE THREAD

**Issue by makkerfeng** [KlausT/ccminer#218]
-i, --intensity=N[,N] GPU threads per call 8-25 (2^N + F, default: 0=auto)
                        Decimals and multiple values are allowed for fine tuning
      --cuda-schedule   Set device threads scheduling mode (default: auto)

but where the "F" come from and how can i write into my batch file?
thanks!

**Comment by KlausT** [comment]
I think you are using tpruvot's ccminer version, not my version.
I'm not sure, but maybe means that you can use fractions, like 16.3 or something.

**Comment by makkerfeng** [comment]
Thanks! but when I trying to set intensity=8.8, it doesn't work with what I think.
