### ISSUE TITLE
About the intensity, source code in "ccminer.cpp"

### ISSUE THREAD

**Issue by makkerfeng** [KlausT/ccminer#223]
CODE:

d = atof(pch);
v = (uint32_t) d;
uint32_t adds = (uint32_t)floor((d - v) * (1 << (v - 8))) * 256;
gpus_intensity[n] = (1 << v) + adds;
applog(LOG_INFO, "Adding %u threads to intensity %u, %u cuda threads",

adds will always be 0 ?

**Comment by KlausT** [comment]
Not if you use something like -i 17.6
`Adding 78592 threads to intensity 17, 209664 cuda threads`

**Comment by makkerfeng** [comment]
thanks!
-i 17.6  
it runing just like what you show me .
but my old card only 512  cuda threads.
when I set   -i 8, it run with 256 threads.
when I set   -i 8.5 or the other like 8.x , adds is always be 0, the miner run still with 256 threads.
could you tell me how to run with n threads (256<n<512) please.

**Comment by KlausT** [comment]
Oh, ok, I see.
I didn't expect that someone is using such a low intensity.
Usually a higher intensity is faster.

**Comment by makkerfeng** [comment]
Thanks for your help!
I'm runninng some Low end video card on ubuntu, and they provided high performance-price ratio for me . so it's useful for me to run with 8.x
