### ISSUE TITLE
Remove unwanted algos

### ISSUE THREAD

**Issue by crazydoc72** [KlausT/ccminer#225]
It´s easy to remove CUDA architectures which you do not need from Makefile.am. What´s about unwanted algos? Any simple solution?

**Comment by KlausT** [comment]
It's not that easy, but possible.
Let's take pentablake for example.
In the ccminer.cpp file there's this code:
```
		case ALGO_PENTABLAKE:
			rc = scanhash_pentablake(thr_id, work.data, work.target,
									 max_nonce, &hashes_done);
			break;
```
This has to be removed.
Then we have to remove files from Makefile.am
In this case that would be pentablake.cu
We can do the same for other algos.

**Comment by crazydoc72** [comment]
Ok, I´ll try!

**Comment by platinum4** [comment]
Has this question been sufficiently answered?  If so, close this issue.
