### ISSUE TITLE
invalid shares when mining 1080ti yescrypt16 Yenten?

### ISSUE THREAD

**Issue by Drag0g0** [KlausT/ccminer#229]
invalid shares when mining 1080ti yescrypt16 Yenten?

I get much invalid shares when mining.

Im new with this miner, is there something special i need to do?

My file look like "ccminer.exe -a yescryptR16 -o stratum+tcp://yenten.luckypool.org:3333 -u ****.*****-p *****-q"

**Comment by KlausT** [comment]
What ccminer version are you using?

**Comment by Drag0g0** [comment]
Newest

**Comment by KlausT** [comment]
Well, I guess you are using tpruvot's version (2.2.4 or something).
I can't help you with that.
Go here:
[https://bitcointalk.org/index.php?topic=770064.0](https://bitcointalk.org/index.php?topic=770064.0)

Or maybe you are confusing ccminer with cpuminer.
In this case go here:
[https://github.com/JayDDee/cpuminer-opt](https://github.com/JayDDee/cpuminer-opt)

**Comment by platinum4** [comment]
Close this issue; this is with a modified KlausT miner from OneDrive
