### ISSUE TITLE
Built-in benchmark is not working.

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/ccminer#23]
Hey.want to benchmark all algos with your miner but it won't start with this error
![image](https://cloud.githubusercontent.com/assets/16507768/23833819/ee158678-0753-11e7-8105-0e51cb5d8dbc.png)
can you fix it?same cmd works fine with djm's ccminer.

**Comment by KlausT** [comment]
You can't benchmark all algos at once like in tpruvot's ccminer.
Anyway, I have removed Bitcredit now since nobody is using it anyway.
