### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SoraKohaku** [KlausT/ccminer#232]
![algo](https://user-images.githubusercontent.com/11433397/38072004-6991928c-335f-11e8-8742-c694dce6a665.png)

cuda9 not support~ so i try 8

**Comment by KlausT** [comment]
What graphics card do you have?

**Comment by SoraKohaku** [comment]
730. Can you add it?I'm not much money to buy new graphics. I not profit
from mining turtle damn.

**Comment by KlausT** [comment]
Nvidia does not support your GT 730 anymore. It's too old.

**Comment by SoraKohaku** [comment]
ah ok thanks. CLOSED case :)
