### ISSUE TITLE
Hashrate

### ISSUE THREAD

**Issue by kuttkutt** [KlausT/ccminer#233]
Hello, 

I use ccminer on my nivida cards.

I have a rig with AMD and Nvidia cards. On Nividia I use ccminer, on AMD I use xmrig-amd.

ccminer shows at the NVIDIA card 280H/s and the AMD cards 150H/s.
However at the pools site I see 150H/s for the AMD ones and only 255 for the NVIDA one. Both over a 24h runtime and 24h mining. 

So I kinda wonder why thats the case? 

More strange - for a test I switchted to xmrig-nvidia for one NVIDA card - OK I mine on that card now only about 2h - but the 1h average went up to 290H/s. In the terminal it tells me that the card manages to get 285 H/s (which is almost the same like ccminer does).

Does anyone have an idea why thats the case? 

I'll definetly try xmrig on my 780ti aswell ... there the 24h average is 380H/s right now. 

EDIT: I just wen to my 780 ti... 2h average at the pool 322 - ccminer tells me at the shell 380

Thats at the ti780 18% less  and at the 960 gtx 12% less...but not at the amd cards or the CPU miners I use o_O

**Comment by kuttkutt** [comment]
Hmm - ok - this is disturbing ...

these are the stats now (after 2h xmrig):

GTX960: 
Current: 318 H/s 
1h average (at xmrig-nvidia):  302 H/s
24 average (at ccminer) 267 H/s


780Ti:
current: 452 H/s
1h (xmrig-nvidia): 406 H/s
24h (ccminer) : 327 H/s

these are the pools statistics, not mine .. I also uses exactly the same setting in config. Interesting: the shell tells me about the same H/s in shell  no matter if I use xmrig or ccminer (same donation level) but the pool does not?

Please reply within 12h or's I'll post this in coinforums (did screenshots)

**Comment by KlausT** [comment]
What algo is this?
What ccminer version is this?
(I think I know the answer, but I want to be sure)

**Comment by kuttkutt** [comment]
ccminer-821-cuda91 & cryptonite

for testing I went with an other GTX 970 for the test (which had a hashrate of 375 over 24h, let's see :)

**Comment by KlausT** [comment]
Cryptonite with ccminer 8.21 ?
No, certainly not.
You are confusing something here.

Is it one of these?
* Cryptonight with [ccminer-cryptonight](https://github.com/KlausT/ccminer-cryptonight) 3.00
* Cryptonight with [ccminer-tpruvot](https://github.com/tpruvot/ccminer) 2.2.4
* Cryptolite with ccminer-tpruvot 2.2.4

**Comment by kuttkutt** [comment]
It's the one from here: https://github.com/KlausT/ccminer/releases

> 8.21
> 
> @KlausT KlausT released this 16 days ago
> Assets
> 
>     17.6 MB
>     ccminer-821-cuda8-x64.zip
>     20 MB
>     ccminer-821-cuda91-x64.zip


(the cuda91 version)

**Comment by KlausT** [comment]
This miner doesn't support cryptonite

**Comment by KlausT** [comment]
Maybe you are using a version that somebody else has modified?

**Comment by kuttikutt** [comment]
Uhm .. you are right:

this is the output: 

> *** ccminer 2.2.4 for nVidia GPUs by tpruvot@github ***
>     Built with VC++ 2013 and nVidia CUDA SDK 9.0 64-bits
> 
>   Originally based on Christian Buchner and Christian H. project
>   Include some kernels from alexis78, djm34, djEzo, tsiv and krnlx.
> 
> BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo (tpruvot)

(My test directory is full of mining tools - posted the wrong one - sorry)

Is this the wrong GitHub to ask this?

**Comment by KlausT** [comment]
You could try asking here:
https://bitcointalk.org/index.php?topic=770064.0
That's the official forum thread for tpruvot's ccminer
The github link:
https://github.com/tpruvot/ccminer
I think he doesn't have an issue section there.

**Comment by platinum4** [comment]
Close this, incorrect place to file an issue for this problem.
