### ISSUE TITLE
Many rejects (stale shares) mining CRYPLY (yescryptr16) on GTX1080Ti

### ISSUE THREAD

**Issue by Yurexxx** [KlausT/ccminer#234]
Using ccminer-KlausT-8.21-mod-r5 to ccminer-KlausT-8.21-mod-r7
Different stratum difficulty - constant or autotuning by the pool.
Hashrate is 3300H/s (GTX1080Ti@2012MHz) using last R7 release (87%-88% accepted shares).

CPU mining (i7 2700K@4500MHz) on the same machine - 870H/s using JayDDee's cpuminer-opt 3.8.5 (99.7% accepted shares).

**Comment by Yurexxx** [comment]
Stats for ccminer-KlausT-8.21-mod-r8
Hashrate is 3160H/s (GTX1080Ti@2012MHz) and 90%-90.2% accepted shares.

**Comment by KlausT** [comment]
Maybe you should ask the person who made the mod.
I didn't add yescryptr16.

**Comment by Yurexxx** [comment]
Ups! Sorry...

**Comment by rinkal26783** [comment]
@KlausT I get only 70% accepted share with your original miner.

**Comment by KlausT** [comment]
Look at my answer above:

> Maybe you should ask the person who made the mod.
> I didn't add yescryptr16.

**Comment by rinkal26783** [comment]
I am using https://github.com/KlausT/ccminer/releases/tag/8.21

**Comment by KlausT** [comment]
Since this issue is about Yescryptr16 I thought you are using that.
What algo are you using?
Windows or Linux?

**Comment by rinkal26783** [comment]
Yes, I am using Yescryptr16 cuda 9.2 windows.
I think there is problem with algo. because its gpu resistant.

**Comment by KlausT** [comment]
My version doesn't support yescrypt.
You are using a version that has been modified by someone.

**Comment by rinkal26783** [comment]
I am talking about algo "yescryptR16"

**Comment by KlausT** [comment]
Sigh.
How can I make myself more clear?
My ccminer doesn't support any version of yescrypt.
