### ISSUE TITLE
Unable to build in ubuntu 18

### ISSUE THREAD

**Issue by arnau-foraster** [KlausT/ccminer#235]
`gcc (Ubuntu 5.5.0-11ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
`
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.42                 Driver Version: 390.42                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 745     Off  | 00000000:01:00.0  On |                  N/A |
| 40%   80C    P0    N/A /  N/A |   1388MiB /  4041MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
`

gcc -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-cpu-miner.o -MD -MP -MF .deps/ccminer-cpu-miner.Tpo -c -o ccminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
gcc -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-util.o -MD -MP -MF .deps/ccminer-util.Tpo -c -o ccminer-util.o `test -f 'util.c' || echo './'`util.c
gcc -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-crc32.o -MD -MP -MF .deps/ccminer-crc32.Tpo -c -o ccminer-crc32.o `test -f 'crc32.c' || echo './'`crc32.c
gcc -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-hefty1.o -MD -MP -MF .deps/ccminer-hefty1.Tpo -c -o ccminer-hefty1.o `test -f 'hefty1.c' || echo './'`hefty1.c
cpu-miner.c:12:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
crc32.c: In function ‘uint32_t crc32(uint32_t, const void*, size_t)’:
crc32.c:97:4: error: invalid conversion from ‘const void*’ to ‘const uint8_t* {aka const unsigned char*}’ [-fpermissive]
  p = buf;
    ^
Makefile:875: recipe for target 'ccminer-crc32.o' failed
make[2]: *** [ccminer-crc32.o] Error 1
make[2]: *** Waiting for unfinished jobs....
util.c:11:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
cpu-miner.c: In function ‘bool work_decode(const json_t*, work*)’:
cpu-miner.c:459:1: error: jump to label ‘err_out’ [-fpermissive]
 err_out:
 ^
cpu-miner.c:431:8: note:   from here
   goto err_out;
        ^
cpu-miner.c:444:10: note:   crosses initialization of ‘json_t* jr’
  json_t *jr = json_object_get(val, "noncerange");
          ^
cpu-miner.c:459:1: error: jump to label ‘err_out’ [-fpermissive]
 err_out:
 ^
cpu-miner.c:427:8: note:   from here
   goto err_out;
        ^
cpu-miner.c:444:10: note:   crosses initialization of ‘json_t* jr’
  json_t *jr = json_object_get(val, "noncerange");
          ^
cpu-miner.c: In function ‘void parse_config()’:
cpu-miner.c:1830:32: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    parse_arg(options[i].val, "");
                                ^
In file included from /usr/include/stdlib.h:566:0,
                 from util.c:15:
util.c: In function ‘void applog(int, const char*, ...)’:
util.c:92:9: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
   buf = alloca(len);
         ^
util.c: In function ‘void* aligned_calloc(int)’:
util.c:496:37: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
  void **ptr = (void**)((size_t)(mem+ALIGN+sizeof(void*)) & ~(ALIGN-1));
                                     ^
util.c:496:55: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
  void **ptr = (void**)((size_t)(mem+ALIGN+sizeof(void*)) & ~(ALIGN-1));
                                                       ^
In file included from util.c:36:0:
util.c: In function ‘void applog_compare_hash(uchar*, uchar*)’:
miner.h:391:17: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 #define CL_GRY  "\x1B[01;30m" /* dark gray */
                 ^
util.c:1475:55: note: in expansion of macro ‘CL_GRY’
   char *color = memcmp(hash+i, hash2+i, 4) ? CL_WHT : CL_GRY;
                                                       ^
Makefile:861: recipe for target 'ccminer-util.o' failed
make[2]: *** [ccminer-util.o] Error 1
Makefile:847: recipe for target 'ccminer-cpu-miner.o' failed
make[2]: *** [ccminer-cpu-miner.o] Error 1
mv -f .deps/ccminer-hefty1.Tpo .deps/ccminer-hefty1.Po

**Comment by KlausT** [comment]
Did you run ./autogen.sh and ,/configure.sh first?
I'm not a Linux expert, so I'm not sure what's wrong there

**Comment by arnau-foraster** [comment]
finally successfully built using windows branch.
