### ISSUE TITLE
Error using x11 algo

### ISSUE THREAD

**Issue by gill3m** [KlausT/ccminer#241]
Platform: Ubuntu 16.04 , CUDA 9.1, GPU: nvidia Tesla K80
GPU #0: Cuda error in func 'x11_echo512_cpu_hash_64_final' at line 674 : an illegal memory access was encountered.
[2018-04-29 14:48:45] stopping 1 threads

Error happens on startup.

**Comment by platinum4** [comment]
Hi, close this issue nobody mines with Tesla K80s

**Comment by KlausT** [comment]
Same issue as here:
https://github.com/KlausT/ccminer/issues/261
