### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by MaynardMiner** [KlausT/ccminer#243]
Hello,

I have been building a multi-algo miner for linux, which is meant to work for an Ubuntu Minimal installation. I followed all INSTALL instructions from Wiki, and even tried removing then running autogen and configure before build.sh. For some reason the miner doesn't complete building. You can go to my page to see how the Ubuntu Minimal Installation is being set-up: https://github.com/MaynardMiner/MM.Hash

I know this is an Ubuntu minimal installation, so I am assuming that I am missing a dependency, however I can install Tpruvot, MSFT-server, and Krnlx versions of CCminer perfectly fine.

I was wondering if this miner may require an additional dependency beyond Tpruvot's version?

**Comment by KlausT** [comment]
I think the dependencies should be the same.
* automake
* libssl-dev
* libcurl4-openssl-dev
* libjansson-dev

**Comment by MaynardMiner** [comment]
libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential

Is what Tpruvot suggests. Would any of that conflict? I see autotools-dev, build-essential is extra.

**Comment by KlausT** [comment]
On my Ubuntu 16.04 I didn't need to install autotools-dev and build-essential, as far as I can remember.
I can't think of anything my version would need that tprovot's doesn't.

**Comment by MaynardMiner** [comment]
gcc-5 g++-5
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
libgmp3-dev
curl

I missed those. His setup includes those as well, which I installed/ran. It's just weird that I can get those CCminers to work, but not this one. I even tried copying their autogen/configure/build.sh into the miner, and tried to compile- still the same.

I will try it again tonight, and get a screen-shot of where/why it failed.

**Comment by MaynardMiner** [comment]
nvcc fatal: Unsupported gpu architecture 'compute_70'

That is the first error message I get before it spirals into recipe for target 'all' failed.

To get cuda toolkit (nvcc) I am using:

apt-get install nvidia-cuda-dev nvidia-cuda-toolkit

Could it be an incompatibility with recent toolkit?

**Comment by KlausT** [comment]
Looks like you are using an old CUDA version.
If you don't have a Titan V card you could remove the compute_70 stuff in line 94, 144 and 144 in the Makefile.am.

**Comment by MaynardMiner** [comment]
I will try it. I didn't realize apt-get nvidia-cuda-toolkit gets you an older version. I found instructions I think on how to get the newer version, purge old, then will try tonight.

**Comment by Novicracker** [comment]
Once you uninstall all of the old Cuda programs installed. You will need to
use --->Display Driver Uninstaller
<http://www.guru3d.com/files-details/display-driver-uninstaller-download.html><---
This will need to be run in Safe Mode. So reboot the system into Safe Mode
first. This is to ensure all of the Display Driver dependencies are removed
as well.

**Comment by MaynardMiner** [comment]
I was able to get it built with Cuda 9.1, but I had to get it to compile gcc 5.4.1 in 17.04. Which took some more tweaking with gcc setting --slave. That was fun and took some extra steps

Now my new issue is that it runs on my 1050ti's fine, but for some reason I get Error in ./ccminer: Free(): invalid pointer: 0x0007fae6cd426f8 when starting up my 1070's.

Is that another build issue I screwed up on?

**Comment by MaynardMiner** [comment]
@Novicracker- Linux system. 

I ran sudo-apt purge Nvidia*

Then installed everything again.

**Comment by MaynardMiner** [comment]
That ./ccminer: Free(): invalid pointer issue still persisted. However, I figured out a way to have your miner featured in my mining application- I am running your windows binary version in Linux in MM.Hash, which works fine when I set it up.

I guess I am making you aware think there may be an issue with cloning current git for linux. Other than that, I solved my personal issue.

**Comment by dergudzon** [comment]
@MaynardMiner hello, how did you fix "invalid pointer issue" problem?
