### ISSUE TITLE
parameters in sia_precalc()

### ISSUE THREAD

**Issue by honlen** [KlausT/ccminer#244]
Would you please kindly tell me how to get the following parameters:
0xBB1838E7A0A44BF9u, 0x510E527FADE68281u, 0x566D1711B009135Au.
In cuda_sia.cu, sia_precalc(), line 306. 
Thank you in advance!

**Comment by KlausT** [comment]
Those are constants from the blake2b algo.
You can see the constants in the blake2b functions in sia.cu too, but a little bit less optimized

**Comment by honlen** [comment]
Got it. Thanks a lot!
