### ISSUE TITLE
Miner error :  15 nonces returning

### ISSUE THREAD

**Issue by Goranbol** [KlausT/ccminer#245]
![image](https://user-images.githubusercontent.com/36314385/40378007-a2dd8e02-5df2-11e8-94d8-da7dc0b9f86a.png)

Hi Klaus,

I have this error log on my miner. Whats a nonce and why is it returning?

I have photo in Att for you to see.

**Comment by KlausT** [comment]
I'm not familiar with this autoswitcher.
Maybe it's complaining about too many shares?
I don't know

**Comment by Goranbol** [comment]
Thank you Klaus for quick answer. 
So Nonce is shares than ?
Just to confirm that.

**Comment by Goranbol** [comment]
Where are you Klaus/

**Comment by KlausT** [comment]
Yes, nonces are practically shares
