### ISSUE TITLE
sm_61 problem

### ISSUE THREAD

**Issue by frkl** [KlausT/ccminer#25]
I managed to build the windows branch on Ubuntu (by adding compat/Makefile and copying bitcredit over from an old repo) but the resulting ccminer crashes on my 1070s. 

In fact Makefile.am line 81&82

nvcc_ARCH  = -gencode=arch=compute_61,code=sm_61
nvcc_ARCH  = -gencode=arch=compute_52,code=sm_52

It seems that it should be 

nvcc_ARCH  = -gencode=arch=compute_61,code=sm_61
nvcc_ARCH  += -gencode=arch=compute_52,code=sm_52

And the build works after this change.

**Comment by KlausT** [comment]
Since I don't use Linux it sometimes happens that I forget to change stuff in the Makefile.
I will fix this.
