### ISSUE TITLE
build regression: "No rule to make target 'x15/whirlpool.cpp', needed by 'x15/ccminer-whirlpool.o'.  Stop."

### ISSUE THREAD

**Issue by salfter** [KlausT/ccminer#252]
Just updated my Gentoo ebuild to pull the latest version and got this when I tried rebuilding.  A build log is attached.

[build.log](https://github.com/KlausT/ccminer/files/2189632/build.log)

**Comment by KlausT** [comment]
I don't know what's wrong there.
It complains about whirlpool.cpp, but it's right there:
https://github.com/KlausT/ccminer/blob/78b052f5286be10e082976dc21bc41754edbf511/Makefile.am#L55

**Comment by KlausT** [comment]
Oh, I see, the filenames are wrong.
Should be fixed now.

**Comment by salfter** [comment]
Looks like that fixed it...thanks!
