### ISSUE TITLE
Compilation fails 8.22.tar.gz

### ISSUE THREAD

**Issue by toptim** [KlausT/ccminer#253]
`In file included from nist5.cpp:12:0:
cuda_helper.h:4:18: fatal error: cuda.h: No such file or directory`
ubuntu 16, cuda 9.2

**Comment by KlausT** [comment]
I have no idea what's wrong there.
Is there a cuda.h file in /usr/local/cuda/include ?

**Comment by toptim** [comment]
Yes, cuda.h file in /usr/local/cuda/include
[https://ibb.co/eXFJ98](url)
Different error, when i copy cuda_helper.h from 8.21 version
`/usr/local/cuda/bin/nvcc -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -I/usr/local/cuda/include -I. -O3 -std=c++11 -Xcompiler -fno-strict-aliasing,-Wall -D_FORCE_INLINES --maxrregcount=128 -o cuda_myriadgroestl.o -c cuda_myriadgroestl.cu
groestl_functions_quad.cu(243): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(50): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(107): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(196): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(256): error: identifier "SHFL" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_0000261a_00000000-7_cuda_groestlcoin.compute_70.cpp1.ii".
Makefile:2223: recipe for target 'cuda_groestlcoin.o' failed
make[2]: *** [cuda_groestlcoin.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/ccminer-myriadgroestl.Tpo .deps/ccminer-myriadgroestl.Po
mv -f .deps/ccminer-groestlcoin.Tpo .deps/ccminer-groestlcoin.Po
groestl_functions_quad.cu(243): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(50): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(107): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(196): error: identifier "SHFL" is undefined

bitslice_transformations_quad.cu(256): error: identifier "SHFL" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_00002629_00000000-7_cuda_myriadgroestl.compute_70.cpp1.ii".
Makefile:2223: recipe for target 'cuda_myriadgroestl.o' failed
make[2]: *** [cuda_myriadgroestl.o] Error 1`

**Comment by KlausT** [comment]
Download the source again.
It should be fixed now.

**Comment by toptim** [comment]
Thanks!!!
Now compilation complete, no errors
