### ISSUE TITLE
X13 BCD Compatible?

### ISSUE THREAD

**Issue by juanpc2018** [KlausT/ccminer#258]
Reading the Readme, "forgive the redundancy..."
[https://github.com/KlausT/ccminer/blob/windows/README.txt](https://github.com/KlausT/ccminer/blob/windows/README.txt)

latest ccminer does Not seem to have the -a BCD algo

BitcoinDiamondBCD is X13 but Not compatible with Standard X13...
vvpool has a BCD N-Miner based on ccminer.

[https://pan.baidu.com/s/1qZW8uq4#list/path=%2F鱼池资料%2F挖矿软件%2FBCD&parentPath=%2F鱼池资料%2F挖矿软件](https://pan.baidu.com/s/1qZW8uq4#list/path=%2F鱼池资料%2F挖矿软件%2FBCD&parentPath=%2F鱼池资料%2F挖矿软件)

sadly they do Not include the Source..

i have asked all CPU Miners to include support for X13 BCD algo...
but so far No body has been able to do it...

[https://github.com/BeastPool/cpuminer-argon2d/issues](https://github.com/BeastPool/cpuminer-argon2d/issues)

**Comment by KlausT** [comment]
I will probably not add the Bitcoin Diamond algo any time soon, I think.

**Comment by juanpc2018** [comment]
its already been done... contact vvpool if you want the source...

**Comment by crazyrigga** [comment]
Till then we will wait eagerly. :)

**Comment by crazyrigga** [comment]
Managed to find open source and linux binaries. I hope it will help.
https://github.com/uraymeiviar/urayminer

**Comment by juanpc2018** [comment]
interesting, 
"vvpool/ccminer" forked from: "ccminer-alexis-1.0", forked from: "tpruvot/ccminer"
https://github.com/yoyosan/ccminer-alexis-1.0
https://github.com/alexis78/ccminer/releases

ureyminer forked from: "MSFTserver/ccminer", forked from: "tpruvot/ccminer"
KlausT/ccminer forked from: "sp-hash/ccminer", forked from: "tpruvot/ccminer"

"Official BCD Miner" forked from: "sgminer"
https://github.com/eveybcd/gpu-miner

vvpool ccminer --help:
*** ccminer alexis-1.0 for nVidia GPUs from alexis78@github ***
*** Built with VC++ 2013 and nVidia CUDA SDK 8.0 (Acceptable)

*** Based on tpruvot@github ccminer
*** Originally based on Christian Buchner and Christian H. project
*** Include some of the work of djm34, sp, tsiv, klausT, and ComputerCraftr.

hsr         X13+SM3          (Hshare)
bcd        X13-luffa+sm3    (Bitcoin Diamond)
luffa       Doomcoin

**Comment by crazyrigga** [comment]
I have serious doubts on chinese pool compiled miners
