### ISSUE TITLE
GPU # 0: Cuda error in func 'x 11 _simd 512 _ cpu_init' at line 758: out of memory.

### ISSUE THREAD

**Issue by ghost** [KlausT/ccminer#259]
I am using Windows 10, Geforce GTX 570.
I tried to use the x11 algorithm, but I get an error.

The default option will result in the following error.
GPU # 0: Cuda error in func 'x 11 _simd 512 _ cpu_init' at line 758: out of memory.

If '-i' is made small, the following error occurs.
GPU # 0: Cuda error in func 'quark_blake 512 _ cpu _ setBlock _ 80' at line 830: invalid device symbol.

**Comment by KlausT** [comment]
Old cards like this are not supported anymore.

**Comment by ghost** [comment]
Thank you for your reply.
Among the past releases, is there a release compatible with gefoece GTX 570?
Also, could you tell me in detail how to build ccmimer corresponding to gefoece GTX 570?
I changed the corresponding part of the makefile, but I could not build it due to some errors.

**Comment by KlausT** [comment]
Sorry that I didn't answer earlier.
As far as I can remember none of my releases are compatible with your card.
You might have a chance with an older tpruvot version using CUDA 8 or earlier:
https://github.com/tpruvot/ccminer/releases
