### ISSUE TITLE
Jackpot coin

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/ccminer#26]
Hello.
noticed that you are working on jackpotcoin now.probably that is an interesting coin but i can't find any info about mining pool or exchange.
can you give me some links, please?=)
thanks

**Comment by KlausT** [comment]
Sweepstakecoin is using this algo.
https://bitcointalk.org/index.php?topic=1903427.0
The pools are offline right now, I think (Suprnova for example).

**Comment by lyolyalya** [comment]
that's why i can't find any pools=)thanks=)
