### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by globaltoken** [KlausT/ccminer#262]
Hello @KlausT,

How can I compile this in Visual Studio?
It does not work for me.

**Comment by KlausT** [comment]
What version of visual studio do you have?

**Comment by globaltoken** [comment]
My Version is 15.8.7.
Oh and I am using VS Community editon 2017

Well, I want to add new algos, could you compile them if it does not 
work for my VS?

**Comment by KlausT** [comment]
Do you want to use CUDA 9.2 ?
15.8 is not compatible with CUDA 9.2, that compiler version is too new.
With CUDA 10 it should work, I think.
What happens?

**Comment by globaltoken** [comment]
Let me try with CUDA 10!

**Comment by globaltoken** [comment]
Seems working. How can I cross compile with Visual Studio for Linux?

**Comment by KlausT** [comment]
If you want binaries for Linux then you have to compile it under Linux.
https://github.com/KlausT/ccminer/wiki/How-to-create-binaries-under-Ubuntu-Linux

**Comment by globaltoken** [comment]
Thanks. Where do I find the binaries? Compiling succeeded

**Comment by KlausT** [comment]
Under Windows it's in Releases/x64
Under linux there should be a file "ccminer" in same directory than build.sh

**Comment by globaltoken** [comment]
Thank you! How can I build distributable binaries, cross compiling? buld.sh is just for local system requirements or?

**Comment by KlausT** [comment]
I don't have much experience with Linux.
With static linking it should work, but I don't know how to do that under Linux

**Comment by globaltoken** [comment]
Alright. Can I distribute the binaries by my own with this License? Wanna add 6 more algos in my fork

**Comment by KlausT** [comment]
Sure, as long as the users could get the source code if they want. That's the way the GPL works.
