### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by soy-sauce-rice** [KlausT/ccminer#264]
Hello @KlausT,
I want to compile this in a new winows pc,
so i have to install all things from 0,
Can I compile the latest version code with Visual Studio Community 2017 and CUDA 10?
Thank you.

**Comment by KlausT** [comment]
I have not tested the latest VS2017 version, but it should work with CUDA 10.

**Comment by soy-sauce-rice** [comment]
Thank you for your reply.
I have installed vs2015 and cuda10.
I am using 64-bit windows10.
Now I have some problems compiling your program.
I did the following things:
1 I downloaded the code from https://github.com/KlausT/ccminer
2 extract the zip file to desktop
3 change "CUDA 9.2" to "CUDA 10.0" in ccminer.vcxproj
4 open ccminer.sln with vs2015
5 choose "debug" and "win32"
6 build 
and the results are as follows
![p1](https://user-images.githubusercontent.com/27428177/47839225-f0fe0600-ddec-11e8-89d8-5c18acc961ad.png)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe" -gencode=arch=compute_50,code=\"sm_50,compute_50\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" -x cu  -I. -Icompat -I"compat\curl-for-windows\curl\include" -Icompat\jansson -Icompat\getopt -Icompat\pthreads -I"compat\curl-for-windows\openssl\openssl\include" -I"compat\curl-for-windows\zlib" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include"  -G   --keep-dir Debug -maxrregcount=80 --ptxas-options=-v --machine 32 --compile -cudart static  -g   -DWIN32 -D_DEBUG -D_CONSOLE -D_CRT_SECURE_NO_WARNINGS -DCURL_STATICLIB -DUSE_WRAPNVML -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FdDebug\vc140.pdb /FS /Zi /RTC1 /MDd " -o Debug\cuda_bmw256.cu.obj "C:\Users\sleewa\Desktop\ccminer-windows\Algo256\cuda_bmw256.cu"" exited with code 1.	ccminer	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 10.0.targets	712	
```
Do you know what is the solution?Looking forward for your reply, thank you

**Comment by KlausT** [comment]
try "release" instead of "debug". I have not updated the debug settings for a while now since I don't use it.
Also, I think Nvidia now only supports 64bit for VS2015 and VS2017. 32bit only works with VS2013 or something.

**Comment by soy-sauce-rice** [comment]
Thank you for your reply.
I compiled this with "release" and "x64".
The vs2015 shows that there are still 3 errors.
Like this:
![p2](https://user-images.githubusercontent.com/27428177/47888546-0b34f400-de80-11e8-963c-a792d3d1b05d.png)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "int __cdecl scanhash_sia(int,unsigned int *,unsigned int *,unsigned int,unsigned int *)" (?scanhash_sia@@YAHHPEAI0I0@Z)	ccminer	C:\Users\sleewa\Desktop\ccminer-windows\ccminer.obj	1	
```
I feel that I am very close to success.Can you help me again?
Looking forward for your reply, thank you.
I rebuild this again,and it run.

**Comment by dream960727** [comment]
ok,

**Comment by weartog** [comment]
Hello, i have same problem for VS2019 and cuda 10.1.

**Comment by weartog** [comment]
> Hello, i have same problem for VS2019 and cuda 10.1.

Use last advice "try release x64". And it's working. Compile with 110 warnings, no errors. It's done.
