### ISSUE TITLE
which hardfork does the SIA algo go with ?  Hyperspace? SiaClassic? SiaPrime? Sia?  ccminer version 8.20

### ISSUE THREAD

**Issue by truelv** [KlausT/ccminer#269]
version：8.20
mining pool：SiaMining  

 I don't know which algo version does ccminer implements so I don't know which port of SiaMining should I connect when I mine SIA .

Thx A Lot!@KlausT

**Comment by truelv** [comment]
**GPU info**：
NAVIDA GTX 1060 6GB
```
wyh@wyh-B85M-D3V:~/wya/sia/ccminer-8.20$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1)

wyh@wyh-B85M-D3V:~/wya/sia/ccminer-8.20$ lspci -v -s 01:00.0
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1) (prog-if 00 [VGA controller])
        Subsystem: Device 7377:0000
        Flags: bus master, fast devsel, latency 0, IRQ 30
        Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Memory at f0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at e000 [size=128]
        [virtual] Expansion ROM at f7000000 [disabled] [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: nvidia
        Kernel modules: nvidiafb, nvidia_410_drm, nvidia_410
```

I see a notice on SiaMining  which says
```
Miners not compatible with Sia's hardfork (currently, this means all non-Obelisk ASICs and most GPU miners, with the exception of Marlin 1.1.0 and newer) trying to mine Sia may be automatically redirected to the SiaClassic pool so that their work doesn't go wasted (check here). 
```
Does this means I can't mine SC with GPU that isn't Marlin 1.1.0 and newer ? 

Hope  for your reply !  Thx a lot !

**Comment by KlausT** [comment]
Right now ccminer still uses the old algo.
Every fork that uses the old algo should be compatible.
I have to fix a bug or two in my code, after that it will be compatible with the new algo too.
Maybe Siamining will not redirect ccminer if I release a new version that's compatible. I don't know.

**Comment by truelv** [comment]
Yeah , I found ccminer can mine SSC  XSC  XSP and not  for SC . Hoping for your editing to solve it . It's too hard to find one GPU miner suitable for SC. 
Thank you . Thank you.

**Comment by platinum4** [comment]
@truelv this question has been answered; can you close this please?
