### ISSUE TITLE
Can't build on Ubuntu 16.04

### ISSUE THREAD

**Issue by nylira** [KlausT/ccminer#27]
With running `./build.sh`:

<img width="639" alt="screen shot 2017-06-05 at 18 02 49" src="https://cloud.githubusercontent.com/assets/172531/26779757/40f294be-4a19-11e7-8898-f59d3eb0ae12.png">

Any help appreciated!

**Comment by KlausT** [comment]
I have made some changes now. Please try the latest version.

**Comment by 88plug** [comment]
See #29

**Comment by nylira** [comment]
@KlausT It works, thank you!
