### ISSUE TITLE
CUDA 10.1 compiler crash (Windows)

### ISSUE THREAD

**Issue by KlausT** [KlausT/ccminer#273]
Is it just my system, or is there a bug in the compiler?
It crashes while trying to compile cuda_neoscrypt.cu.
Under Linux it works just fine, only under Windows there's this problem.
Has anybody here more luck than me?

**Comment by maria1118** [comment]
mine is also crashing

**Comment by Minerx117** [comment]
this has been fixed with update 2 for cuda 10.1 


compiled latest windows branch on 01/03/2020
Visual Studio 2019 Cuda 10.1 update 2
https://imgur.com/a/OUZf8Ux
