### ISSUE TITLE
is it support bench32 format address?

### ISSUE THREAD

**Issue by mraksoll4** [KlausT/ccminer#275]
is it support bench32 format address?

**Comment by KlausT** [comment]
ccminer doesn't care about the address format, it's the pool that's checking it

**Comment by mraksoll4** [comment]
Yes maybe , but if you plan add solo mining from wallets with create coinbase tx , some of latest coins support bench32 segwit addreses  if updated to latest btc source or bassed at them.

**Comment by KlausT** [comment]
Maybe I will add this in the future, but I will have to see how complicated the coinbase thing will be.

**Comment by mraksoll4** [comment]
i was try it add self from cpuminet sources .
there was fixes for segwit coinbase and for bech32.
But first need add logic of coin basse.
https://github.com/pooler/cpuminer/commit/7e8960212f0055d6dafaa3c80812c50cec291de3
https://github.com/pooler/cpuminer/commit/46e919f93cb16756a92fe8c957e78ed1fc634384

+ i think good feature be for future add realization for solo mining variable markle root be puting  address pool from file or add generation at fly at cpu . For any new request for block from rpc , use new unique address + coin base = new markleroot.
I was try this with manual simulation vatiable markle root , and it some times make sped up of find blocks . but if realy this is make mining more random )  For coins with with stable tx rate this not very matter , but for coins with low tx rate + if solo mining - no extranonce, if no pool. This can make huge differents :)
