### ISSUE TITLE
Win10, freez after start

### ISSUE THREAD

**Issue by ValenMX** [KlausT/ccminer#30]
Hey, found strange bug.
I have few 1070nvidia rigs. All running win10 with MPM autoswitch script against same pool.
On machines with 1 and 2 cards your ccminer always working good.
On machines with 3 and 7 cards sometimes it do nothing after start, like after "starting 3 threads" no errors, just do nothing. Not always, but pretty often.
As it works fine with all the same env. for 1-2 threads, I expect something related with amount of threads. Only difference that rigs with 1-2 cards is usual home computers with decent amount of ram and ok processors, and 3+ cards rigs is dedicated machines with 4gb ram and celeron 3930 processors. I cant provide any logs, as problem leave no traces. Any ideas? Used 8.06 and 8.08

**Comment by lyolyalya** [comment]
if you are mining skein or maybe x17 or c11 or nist5 or whirlpool aaan do so on then it's CPU problem.was mining with 2 cards without any problema on athlon II x2 220.then 3 cards was working strange...and when i added 4th card then i get same problem you describe.i changed CPU to FX-4300 and problems are gone.
seems like low-end cpus can't start so many cuda threads at once.

**Comment by platinum4** [comment]
Hi, close this issue there's been at least 3 major Windows 10 updates since this issue was opened.
