### ISSUE TITLE
OpenSSL library required

### ISSUE THREAD

**Issue by M62** [KlausT/ccminer#33]
Debian 9 (Sid) kernel 4.9.0-3-amd64

```
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL library required
```

libssl-dev installed

**Comment by KlausT** [comment]
I have no idea how this configure stuff works.
Did you use the build.sh script?

**Comment by M62** [comment]
Result:

```
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL library required
```

Because in the ./build.sh calls ./configure.sh

```
#!/bin/bash
# Simple script to create the Makefile and build
# export PATH="$PATH:/usr/local/cuda/bin/"
make distclean || echo clean
rm -f Makefile.in
rm -f config.status
./autogen.sh || echo done
# CFLAGS="-O2" ./configure
./configure.sh
make -j4
```

I will ask the solution in the Debian IRC channel.
If a solution is found, I will write here.
Probably the problem in version of the libsll-dev library.

**Comment by M62** [comment]
The problem was in libssh-dev. Reinstallation solved the problem.
