### ISSUE TITLE
neoscrypt solo mining

### ISSUE THREAD

**Issue by dmitweb** [KlausT/ccminer#35]
When i try to run mining:

> [2017-07-14 04:35:08] [31m JSON inval data [0m
> [2017-07-14 04:35:08] [36m 127.0.0.1:9337 neoscrypt block 1798144 [0m
> [2017-07-14 04:35:08] [31m json_rpc_call failed, terminating workio thread [0m
> [2017-07-14 04:35:08] workio thread dead, exiting. [0m

But, tpruvot/ccminer work's fine.

**Comment by dmitweb** [comment]
@KlausT can you check this please, or you fork can not work in solo mode?

**Comment by KlausT** [comment]
I'm trying to sync the wallet right now.
When it's ready I will test mining.

**Comment by dmitweb** [comment]
@KlausT I run walllet and server to not wait for the synchronization, try it:
http://5653fb57.ngrok.io
Orbitcoin, neoscrypt, user: dmitweb, pass: x

**Comment by KlausT** [comment]
Looks like I have to do more changes than I thought.
Mining Orbitcoin works here now with my change, but I will do more changes so that Feathercoin works too.
Please check the 8.10 prerelease version if it works for you.
