### ISSUE TITLE
Can't compile using autotools

### ISSUE THREAD

**Issue by pallas1** [KlausT/ccminer#40]
make[2]: *** No rule to make target 'sph/neoscrypt.c', needed by 'sph/ccminer-neoscrypt.o'.  Stop.

**Comment by KlausT** [comment]
Um. Yeah. I renamed it to neoscrypt.cpp, I think.

**Comment by KlausT** [comment]
Did you use the build.sh script?

**Comment by pallas1** [comment]
The usual autogen.sh, configure, make
Makefile.am looks good to me as it is. 

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KlausT** [comment]
Looks like you have an old Makefile.
I don't know why it doesn't get overwritten by a new one.
Maybe the build.sh script is doing something different?

**Comment by pallas1** [comment]
It does "make distclean" instead of "make clean", and deletes all ".in" files.
Weird behavior, but it works :-)
Probably some obscure m4 macro.
Unfortunately noescrypt then fails:
Cuda error in func 'neoscrypt_cpu_init_2stream' at line 1431 : invalid device symbol.

**Comment by KlausT** [comment]
What GPU do you have?
Are you using CUDA 8.0 ?

**Comment by pallas1** [comment]
1070, cuda8

**Comment by lyolyalya** [comment]
i compiled latest source on windows without any problems.
win10, VS2015 Ent

**Comment by KlausT** [comment]
I can't reproduce this error.
I have a 1070 too, and there's no problem.
But I don't use Linux.

**Comment by pallas1** [comment]
can't reproduce any longer, closing.
