### ISSUE TITLE
No solo mining of Phoenixcoins

### ISSUE THREAD

**Issue by Samhayne** [KlausT/ccminer#42]
Hi again. :)

Found another coin that can't be mined.
But this time it should work with ccminer as tpruvot's version works (=finds blocks).

> [2017-07-25 21:02:29] NVML GPU monitoring enabled.
> [2017-07-25 21:02:29] 1 miner thread started, using 'neoscrypt' algorithm.
> [2017-07-25 21:02:29] JSON inval data
> [2017-07-25 21:02:29] gbt not supported, block height notices disabled
> [2017-07-25 21:02:29] json_rpc_call failed, retry after 10 seconds

**Comment by KlausT** [comment]
Please test the latest version (8.11). I have made some fixes in the last days.
Maybe the Feathercoin fix has fixed Phoenixcoin too.
There's about a 50% chance it will work :-)

**Comment by Samhayne** [comment]
*harrumph* Hehe. I really feel ashamed now.
You're too fast! :)

Tried versions 8.08 to 8.10 and overlooked that you released version 8.11 two hours prior to my posting which... works!

Thank you, KlausT! :)
