### ISSUE TITLE
Nist efficiency problem

### ISSUE THREAD

**Issue by p1r473** [KlausT/ccminer#44]
Having an issue where Nist5 through ccminer is not using much GPU usage, causing low hash rates.
All other algorithms work.
Works fine on my 2x 1080TI rig but not my 6x 1080TI rig.

![image](https://user-images.githubusercontent.com/9235633/28739147-6a136040-73c6-11e7-8b28-6ebde9c2e65d.png)

**Comment by KlausT** [comment]
I see no reason why it shouldn't work with 6 cards.
Is it the same with other algos?

**Comment by p1r473** [comment]
Nope, other algorithms work great.

**Comment by p1r473** [comment]
What is the default intensity?

**Comment by p1r473** [comment]
OK changing the parameter to -i 25 fixed it. The default did not work on my rig of 6x 1080 ti

**Comment by platinum4** [comment]
Close this issue nobody mines NIST5 on NVIDIA anymore; ASIC only.
