### ISSUE TITLE
Neoscrypt 1080ti Hashrate

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/ccminer#50]
Hello.can you increase hashing speed on neoscrypt for 1080ti like tpruvot does?(1.3-1.4 KH)
i have mixed config with 1070 and 1080ti and can't use his miner cause it works badly with 1070 cards.
thanks.
UPD.sorry, saw that your miner gives that hashrate too on zpools bench. how can i achieve this hashrate with my 1080ti? intensity or something?
your miner shows me only 740 Kh on 1080ti

**Comment by KlausT** [comment]
The 1080Ti is a little bit wierd.
Maybe I can add tpruvot's code and then use it only for 1080 Ti, or something like that.

**Comment by lyolyalya** [comment]
would be nice if you can.alexis miner works same as yours.so as far as i know - there is no alternatives...

**Comment by KlausT** [comment]
Would you like to test this? I can't since I don't have a 1080Ti.
[ccminer-neoscrypt-1080ti-test.zip](https://github.com/KlausT/ccminer/files/1236886/ccminer-neoscrypt-1080ti-test.zip)

**Comment by lyolyalya** [comment]
sure.will report few hours later

**Comment by lyolyalya** [comment]
yeah.that's what i'm talking about!!
http://img.techpowerup.org/170820/b7fzp5tm1q.jpg
thanks.

**Comment by joesixpack** [comment]
Latest ccminer crashes on exiting, but not this test one.
