### ISSUE TITLE
Neoscrypt on 660 ti

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/ccminer#53]
Hey...tried 8.13 with my 660ti(sm_30) and mining is failed.
http://img.techpowerup.org/170829/zp5tm1qbi6303.jpg

**Comment by KlausT** [comment]
I just discovered that there's some code missing for those cards.
It can't work right now

**Comment by PRINCEAHB** [comment]
nice one

**Comment by KlausT** [comment]
Sorry, I accidentally thought that tpruvot's fork contained the code for this cards.
Turns out that this is not the case.
Unfortunately I don't have the skills to write the missing code.

**Comment by lyolyalya** [comment]
it's a pitty...
