### ISSUE TITLE
cuda9 compatible

### ISSUE THREAD

**Issue by Himan2001** [KlausT/ccminer#54]
Hello...

``
./cuda_vector.h(1375): warning: function "__shfl(unsigned int, int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(167): here was declared deprecated ("__shfl() is deprecated in favor of __shfl_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
``

I got this warnings in an endless loop. For the upcomming cuda9 final i suggest, to modify the code to the actual cuda9 definitions. Just to make sure, that in future versions no depracted functions are in use.

**Comment by KlausT** [comment]
Yeah. I don't have access to Cuda 9 yet since I'm not a registered developer. I will have to wait until CUDA 9 release to see what has changed.

**Comment by Himan2001** [comment]
That´s simple: just register with your favorite email-addy, verify your account and download :)
i made the same a few hours ago. i noted on skunkhash a huge improvement. Just make sure to disable
all SM-Versions < 30! - SM20 is no longer supported!

**Comment by KlausT** [comment]
I changed the shfl stuff now in the cuda 9 branch.
But it looks like lyra2v2 is broken.

**Comment by platinum4** [comment]
This is deprecated now that CUDA 9.1/9.2/10 builds are out for KlausT; close this issue.
