### ISSUE TITLE
Xevan on ccminer/8.13-KlausT

### ISSUE THREAD

**Issue by spider703** [KlausT/ccminer#60]
as they launched it ??
![2017-09-30_193533](https://user-images.githubusercontent.com/30767482/31043811-979aa938-a616-11e7-8db6-d7ef555fa5db.jpg)

**Comment by pinkzebrus** [comment]
on lunux recompilate

**Comment by spider703** [comment]
on Linux hevan works, and under Windows 7 is not present? where to get the Linux version?

**Comment by pinkzebrus** [comment]
not, hand add probably added a check after x11 on cpu xevan )

**Comment by spider703** [comment]
I'm interested in the GPU

**Comment by spider703** [comment]
may be this help create miner xevan for windows https://github.com/dArkjON/xevan_ccminer

**Comment by spider703** [comment]
i dont know how to create miner

**Comment by KlausT** [comment]
My ccminer version does not support Xevan.
It looks like dArkjON has added Xevan, but it is not public.

**Comment by bathrobehero** [comment]
Yes, https://github.com/dArkjON/xevan_ccminer doesn't include Xevan despite the name.

**Comment by spider703** [comment]
KlausT can you add this algorithm to the miner, on the map 1080ti gives 21 Mh
