### ISSUE TITLE
Cuda error in func 'scanhash_bitcoin' at line 200 : no kernel image is available for execution on the device.

### ISSUE THREAD

**Issue by NexSqaud** [KlausT/ccminer#70]
![screenshot_142](https://user-images.githubusercontent.com/27753846/32412935-459f8b74-c238-11e7-94a5-d47086070256.jpg)

**Comment by lyolyalya** [comment]
as far as i know klausT removed bitcoin support from it's fork.
why do you need bitcoin algo?

**Comment by KlausT** [comment]
It's probably an old card, like a GTX 560 or something.
These are not supported anymore.
