### ISSUE TITLE
Cuda error in func 'neoscrypt_cpu_hash_k4_2stream' at line 1468 : unspecified launch failure.

### ISSUE THREAD

**Issue by cjroepe** [KlausT/ccminer#77]
Receive this error about 1 min after starting the miner...repeats everytime

**Comment by lyolyalya** [comment]
i beat it with a little memory downclock.

**Comment by cjroepe** [comment]
Thanks I'll try and report back

**Comment by cjroepe** [comment]
This did fix the issue, thanks!!!
