### ISSUE TITLE
stratum_recv_line failed on ubuntu server 17.10

### ISSUE THREAD

**Issue by crazy7bird** [KlausT/ccminer#81]
Hello, i have compile ccminer for ubuntu server.
It's seems i cant connect to any pool.
I use a configuration who work on ccminer windows.
Any way to resolve the problem ?

**Comment by ksze** [comment]
May I ask you how you got ccminer to compile at all? Are you using CUDA? I have trouble building it on Ubuntu 17.10. #80

**Comment by KlausT** [comment]
When you can't connect then it's either a typo in your command line, or a Linux problem.

**Comment by crazy7bird** [comment]
yes i use to fail in typo, but i check and re-check before post the request : 
ccminer -o stratum+tcp://pool.minexmr.com:4444 -u Wallet -p x
And for linux i can ping the stratum pool.
But nevermind i switch to windows much more easy. (Sorry i'm weak XD)
