### ISSUE TITLE
linux gtx 1060 3gb problem

### ISSUE THREAD

**Issue by sats0k** [KlausT/ccminer#83]
i compiled the miner on suse leap 42.3 successful but when i run the miner i get this error.

`Cuda error in func 'neoscrypt_cpu_init_2stream' at line 1439 : invalid device symbol.`

**Comment by KlausT** [comment]
What card are you using?

**Comment by sats0k** [comment]
gtx 1060 3gb

**Comment by sats0k** [comment]
Forgot to say when i try to compile with compute_61 get the error

`nvcc fatal   : Unsupported gpu architecture 'compute_61'`

I have disable compute_61 and compiled with compute_52  everything goes ok
and something else using still cuda 7.5 maybe i must install newer version.

**Comment by sats0k** [comment]
Ok fixed the problem was with cuda installing cuda 8 and compiled with compute_61 all goes well and miner is working but i have less speed about 5%

**Comment by sats0k** [comment]
Finally install cuda 9 and i get the same speed like cuda 7.5
