### ISSUE TITLE
8.15, Lyra2v2, result does not validate on CPU

### ISSUE THREAD

**Issue by papampi** [KlausT/ccminer#84]
Is the "result does not validate on CPU" known issue?
Ubuntu 16.04, Cuda 8, Nvidia driver 387-34

```
ccminer 8.15-KlausT (64bit) for nVidia GPUs
Compiled with GCC 5.4 using Nvidia CUDA Toolkit 8.0

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations implemented by sp-hash, klaust, tpruvot and tsiv.

[2017-12-10 03:56:33] NVML GPU monitoring enabled.
[2017-12-10 03:56:33] Intensity set to 21, 2097152 cuda threads
[2017-12-10 03:56:33] Starting Stratum on stratum+tcp://hub.miningpoolhub.com:20507
0
[2017-12-10 03:56:33] 1 miner thread started, using 'lyra2v2' algorithm.
[2017-12-10 03:56:33] Stratum difficulty set to 256
[2017-12-10 03:56:34] GPU #0: result does not validate on CPU!
[2017-12-10 03:56:43] hub.miningpoolhub.com:20507 lyra2v2 block 839132
[2017-12-10 03:56:43] GPU #0: Zotac GTX 1070, 34.44 MH/s
[2017-12-10 03:56:47] GPU #0: result does not validate on CPU!
[2017-12-10 03:57:08] GPU #0: Zotac GTX 1070, 34.40 MH/s
[2017-12-10 03:57:33] GPU #0: Zotac GTX 1070, 34.43 MH/s
[2017-12-10 03:57:38] Stratum difficulty set to 179.2
[2017-12-10 03:57:38] hub.miningpoolhub.com:20507 lyra2v2 block 839132
[2017-12-10 03:57:38] GPU #0: Zotac GTX 1070, 34.31 MH/s
[2017-12-10 03:57:43] GPU #0: result does not validate on CPU!
```

**Comment by KlausT** [comment]
On Windows it works fine with CUDA 8, only with CUDA 9 I'm getting this error.
I don't know what's causing this.

https://github.com/KlausT/ccminer/issues/69

**Comment by ksze** [comment]
I just tried building from the latest commit 6bf402bd44d805fedfc39ba5cd1c6379237417cc.

CUDA 9.1, GCC 5.4 on Ubuntu 16.04.3 Server Edition amd64:

```
$ ./ccminer --help
ccminer 8.16-KlausT (64bit) for nVidia GPUs
Compiled with GCC 5.4 using Nvidia CUDA Toolkit 9.1
[...]
```

Still the same "result does not validate on CPU!"

**Comment by KlausT** [comment]
I can't reproduce this, On my system everything's fine.
What card do you have?
Overclocked ?

**Comment by ksze** [comment]
ZOTAC GTX 960, stock.

**Comment by KlausT** [comment]
Must be a Linux problem.
I can't help you there.
![screenshot](https://i.imgpile.com/nYLjEu.png)

**Comment by toptim** [comment]
![screen shot 2017-12-24 at 12 02 18](https://user-images.githubusercontent.com/34491370/34325435-7f87b9b6-e8a2-11e7-89b0-dcb2369f69d5.png)
not linux problem
vertminer work good on ubuntu 16 cuda 9.1

**Comment by natewalck** [comment]
This happens on CentOS 7 with a 1070 Ti and Cuda 9.1 as well. I can mine just fine using djm34, tpruvot, etc. 

There must be some code difference which is causing this, if I get time I'll try to diff stuff a bit, but I doubt I'll be successful (Not great @ C++).

**Comment by ng0177** [comment]
I am having the very same problem. gcc on CentOS 7 is v4.9 instead of the required v5 as mentioned in INSTALL. I am going to use https://jdhao.github.io/2017/09/04/install-gcc-newer-version-on-centos/ to install v5 later this week.

**Comment by ng0177** [comment]
gcc v5 on Centos 7 makes no difference - problem persists.

**Comment by SharkWipf** [comment]
gcc v7, Cuda 9.1 on Gentoo, latest git cuda9 branch (cbff9f9), same problem with Lyra2v2 on 8 1080 Tis.  
Other miners (tpruvot, alexis) work fine.  
Adding `--no-cpu-verify` seems to work, albeit more memory- and energy-hungry than Alexis' version at slightly lower hashrates (any plans to merge Alexis' changes into yours?).

**Comment by KlausT** [comment]
I want to fix the bugs first, then i will see if I can optimize things.

**Comment by LordCryptocurrency** [comment]
Hello everybody, How are you?
I wish someone could have a solution to my problem.
If someone can help me I will be extremely grateful!
I have this error that persecutes me for 2 months and I can not find solution:

GPU #1: unspecified launch failure
GPU #1: result for 7fffffff does not validade on CPU!
GPU #1: result for ffffffff does not validade on CPU!
GPU #0 unspecified launch failure
GPU #0: result for 00000000 does not validade on CPU!
GPU #0: result for 00000001 does not validade on CPU!
GPU #0: result for 00000003 does not validade on CPU!

**Video cards Geforce Nvidia 1080TI Zotac Extreme edition

![photo_2018-01-20_17-08-08](https://user-images.githubusercontent.com/30157103/35187575-bab484e8-fe04-11e7-8be1-c0e88247966e.jpg)

**Comment by SharkWipf** [comment]
@LordCryptocurrency I gave a workaround like 2 messages above yours, have you tried that?

**Comment by ng0177** [comment]
Hi, I switched to Fedora and https://github.com/tpruvot/ccminer which works
fine... Regards, Thomas

**Comment by LordCryptocurrency** [comment]
@SharkWipf and @ng0177 Thanks for the help, I use windows and not linux to mine, I tried to include this code `--no-cpu-verify` at the end of the scrypt command line and it did not work, the miner closes. I'm studying, but I still do not know how to use linux.

**Comment by KlausT** [comment]
Looks like there's something wrong with your system.
Make sure you are using the latest driver version.
Reboot your system.
If you are overclocking then please reduce it.

**Comment by LordCryptocurrency** [comment]
@KlausT I'm really grateful for your help.
I formatted 3x my RIG because of this error, the following drivers are updated:
*Ccminer 2.2.4-x64-2.2.4-cuda9
*Windows
*GeForce Driver ver. 390.65
*Visual Basic C ++
*Net Framework

 I've always used the following overclocking configuration to mine Lyra2v2:
Power Limit: 70
Core Clock: 100
Memory Clock: -502

Would someone have a better configuration?
