### ISSUE TITLE
Directory error

### ISSUE THREAD

**Issue by AdemilsonSouza** [KlausT/ccminer#88]
Hello Friend

I use Debian 9.2 and my gave the following error:
_"
make
make  all-recursive
make[1]: Entering directory '/home/ademilson/ccminer'
Making all in compat
make[2]: Entering directory '/home/ademilson/ccminer/compat'
Making all in jansson
make[3]: Entering directory '/home/ademilson/ccminer/compat/jansson'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ademilson/ccminer/compat/jansson'
make[3]: Entering directory '/home/ademilson/ccminer/compat'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/ademilson/ccminer/compat'
make[2]: Leaving directory '/home/ademilson/ccminer/compat'
make[2]: Entering directory '/home/ademilson/ccminer'
nvcc -ccbin clang-3.8 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_30,code=sm_30 -I/usr/local/cuda/include -I. -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o Algo256/cuda_fugue256.o -c Algo256/cuda_fugue256.cu
In file included from <built-in>:325:
In file included from <command line>:9:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/common_functions.h:50:
/usr/local/cuda/include/crt/common_functions.h:64:9: warning: '__CUDACC_VER__' macro redefined [-Wmacro-redefined]
#define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC...
        ^
<command line>:5:9: note: previous definition is here
#define __CUDACC_VER__ 80044
        ^
In file included from Algo256/cuda_fugue256.cu:4:
In file included from ./sph/sph_fugue.h:5:
In file included from ./sph/sph_types.h:828:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/cstdint:35:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/c++0x_warning.h:32:2: error: This file requires
      compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11
      compiler options.
#error This file requires compiler and library support \
 ^
1 warning and 1 error generated.
Makefile:1882: recipe for target 'Algo256/cuda_fugue256.o' failed
make[2]: *** [Algo256/cuda_fugue256.o] Error 1
make[2]: Leaving directory '/home/ademilson/ccminer'
Makefile:1436: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ademilson/ccminer'
Makefile:503: recipe for target 'all' failed
make: *** [all] Error 2
¨_

Could you tell me if there are any specific directories to run make? I am the user ademilson so I believe that the error is not access permission.

Thank you

**Comment by KlausT** [comment]
Did you try the build.sh script?
By the way, debian is not officially supported by Nvidia.

**Comment by AdemilsonSouza** [comment]
I understood, yes I tried the build.sh, I will try in a different distribution. If I succeed in debian, I put the solution here.

Thank you

**Comment by AdemilsonSouza** [comment]
Good evening

As promised, I come with the solution found:

1. Run ./autogen.sh
2. Run sed -i s / SSL_library_init / OPENSSL_init_ssl / configure.ac configure
3. Run ./configure
4. Run ./build.sh

Success in compilation.

Thank you very much
