### ISSUE TITLE
Need help setting up the miner

### ISSUE THREAD

**Issue by quickgibva** [KlausT/ccminer#91]
Hello there ! 

I'm actually trying to setup your version of ccminer which i heard a lot of good thing about.
So i downloaded the 8.16 version :  ccminer-816-cuda91-x64.zip 
But i don't see any .bat file to configure, i only see the .exe one.
I'm fairly new to this and as i usually setup the .bat to write down the pool i'm using, my wallet adress etc, i have some trouble :) 
And if i run the .exe the windows disappear instantly.
If you could help me sort this out i would really appreciate it !
Thanks a lot 👍

**Comment by natewalck** [comment]
Try this:
Open Command Line in windows, then run:

`ccminer.exe --help`

From there, you can add commands for what you want to mine. Also, Google around. There are tons of websites and posts that discuss how to use ccminer.

**Comment by KlausT** [comment]
You could create a bat file and use something like this:
```
@echo off
c:\somewhere\ccminer.exe -o stratum+tcp://mypool -O myusername:mypassword -a neoscrypt
pause
```

**Comment by quickgibva** [comment]
Hey guys, thanks for the answers, yeah i figured it out ! i didn't knew i had to create my own .bat file, i didn't knew how to do it either but google helped me on that part ahah

And now it's working, and oh boy ! it's working veeery well ! i was at around 950 kh/s with 1070 gpu's and i'm now at 1160+ kh/s 

You did an awesome work KlausT :) 

Since i'm here, can we use your program for other algorythm like equihash or lyra ? 

Thanks again for the help !!

**Comment by ManuelTopf** [comment]
Hey Guys can somebody help me with the bat. file ..... what i must write in the txt.file ? and than i must safe it asa ueft-8 ? right ?

**Comment by DarkMatterMatt** [comment]
open Notepad
paste this after changing the path (location of ccminer.exe which you downloaded), mining pool details (url, user, pass, find these on your pool's website/forums) and algorithm:
```
@echo off
c:\somewhere\ccminer.exe --url=stratum+tcp://mypool --user=username --pass=mypassword --algo=neoscrypt
pause
```
save the file as `"ccminer.bat"`, the quotes *are* necessary or it will save as a text file

**Comment by afaq78** [comment]
hello friends

i need some help regarding setup the mining of 2 coins with 1 gpu 

i want to mine more then 1 coins with my single gpu card with automatic switching after some hours

is there any setup configuration for 2 or more coin 

Thanks

**Comment by KlausT** [comment]
This version of ccminer doesn't have an option to automatically switch after a certain time.
There is probably a tool somewhere that does this, but I can't help you with that.

**Comment by afaq78** [comment]
thanks KlausT for the reply
