### ISSUE TITLE
Crashes, computer halts

### ISSUE THREAD

**Issue by a-zb** [KlausT/ccminer#95]
Tried latest release 8.16.
Have 3x GTX 750Ti, Windows 10 x64, latest Nvidia driver, cuda 9.1

Within minutes of starting the ccminer crashes my rig and it halts.
This happened three times in a row. I adjusted settings to default non-overclock , etc, but it didn't help.

On the contrary, the stock ccminer from 'tpruvot' is stable for days at a time.
Is there any debugging or crash dump or event data that I can provide to help out with this, if it's even worth it. 

I don't think the 4% boost over the 'tpruvot' version is worth it for me, but I can help by providing any data that I can.

**Comment by KlausT** [comment]
What algo?
Default intensity?

**Comment by a-zb** [comment]
Of course, my bad - neoscrypt, GoByte coin.
Default intensity as I don't use that option

Yes, I use nvidia xoc for monitoring. Cards are cool with additional fans for active cooling. all cards < 70C

Additionally, I switched to this version from tpruvot version by re-using the same command-line options. Would that be a mistake and should I adjust anything ?

**Comment by KlausT** [comment]
Do you have a tool where you can see the temperatures of your cards?

**Comment by platinum4** [comment]
Hi, it's been a year since this person's rig crashed-- close this issue it's obviously not still an open ongoing problem.
